//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScintillaNET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScintillaNET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create the Scintilla direct message function..
        /// </summary>
        internal static string Exception_CannotCreateDirectFunction {
            get {
                return ResourceManager.GetString("Exception_CannotCreateDirectFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the &apos;{0}&apos; module into memory..
        /// </summary>
        internal static string Exception_CannotLoadModule {
            get {
                return ResourceManager.GetString("Exception_CannotLoadModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; argument cannot be an empty string..
        /// </summary>
        internal static string Exception_EmptyStringArgument {
            get {
                return ResourceManager.GetString("Exception_EmptyStringArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration already finished..
        /// </summary>
        internal static string Exception_EnumeratorEnded {
            get {
                return ResourceManager.GetString("Exception_EnumeratorEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has not started. Call MoveNext..
        /// </summary>
        internal static string Exception_EnumeratorNotStarted {
            get {
                return ResourceManager.GetString("Exception_EnumeratorNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-thread operation not valid: Control &apos;{0}&apos; accessed from a thread other than the thread it was created on..
        /// </summary>
        internal static string Exception_IllegalCrossThreadCall {
            get {
                return ResourceManager.GetString("Exception_IllegalCrossThreadCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than the size of the collection..
        /// </summary>
        internal static string Exception_IndexOutOfRange {
            get {
                return ResourceManager.GetString("Exception_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient space in the target location to copy the information..
        /// </summary>
        internal static string Exception_InsufficientSpace {
            get {
                return ResourceManager.GetString("Exception_InsufficientSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A change in the control who created this annotation has rendered the object invalid..
        /// </summary>
        internal static string Exception_InvalidAnnotation {
            get {
                return ResourceManager.GetString("Exception_InvalidAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} line must specify a valid line within the document..
        /// </summary>
        internal static string Exception_InvalidLine {
            get {
                return ResourceManager.GetString("Exception_InvalidLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start line and end line must specify a valid range..
        /// </summary>
        internal static string Exception_InvalidLineRange {
            get {
                return ResourceManager.GetString("Exception_InvalidLineRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid Scintilla module..
        /// </summary>
        internal static string Exception_InvalidModule {
            get {
                return ResourceManager.GetString("Exception_InvalidModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start line must be greater than or equal to zero..
        /// </summary>
        internal static string Exception_InvalidStartLine {
            get {
                return ResourceManager.GetString("Exception_InvalidStartLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module name must be set before any Scintilla object are created..
        /// </summary>
        internal static string Exception_ModuleAlreadyLoaded {
            get {
                return ResourceManager.GetString("Exception_ModuleAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was out of range. Must be non-negative and less than {1}..
        /// </summary>
        internal static string Exception_MustBeNonNegativeAndLessThan {
            get {
                return ResourceManager.GetString("Exception_MustBeNonNegativeAndLessThan", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GoToNextMessage {
            get {
                object obj = ResourceManager.GetObject("GoToNextMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoToNextMessage___Copy {
            get {
                object obj = ResourceManager.GetObject("GoToNextMessage - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoToPreviousMessage {
            get {
                object obj = ResourceManager.GetObject("GoToPreviousMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineColorHS {
            get {
                object obj = ResourceManager.GetObject("LineColorHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SciLexer.dll.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SciLexer64.dll.
        /// </summary>
        internal static string ModuleName64 {
            get {
                return ResourceManager.GetString("ModuleName64", resourceCulture);
            }
        }
    }
}
