<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks Condition="'$(PABCNET_LEGACY_ONLY)' != 'true'">net40;net10.0</TargetFrameworks>
    <TargetFramework Condition="'$(PABCNET_LEGACY_ONLY)' == 'true'">net40</TargetFramework>
    
    <RootNamespace>Languages.SPython.Frontend.Wrapping</RootNamespace>
    
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Errors\Errors.csproj" />
    <ProjectReference Include="..\..\..\LanguageIntegrator\LanguageIntegrator.csproj" />
    <ProjectReference Include="..\..\..\Localization\Localization.csproj" />
    <ProjectReference Include="..\..\..\ParserTools\ParserTools.csproj" />
    <ProjectReference Include="..\..\..\SyntaxTree\SyntaxTree.csproj" />
    <ProjectReference Include="..\..\..\SyntaxVisitors\SyntaxVisitors.csproj" />
  </ItemGroup>
</Project>
