// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  DESKTOP-56159VE
// DateTime: 08.03.2025 16:35:06
// UserName: ????
// Input file <SPythonParser.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using PascalABCCompiler.SyntaxTree;
using PascalABCCompiler.ParserTools;
using PascalABCCompiler.Errors;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using SPythonParser;

namespace SPythonParserYacc
{
public enum Tokens {
    error=1,EOF=2,FOR=3,IN=4,WHILE=5,IF=6,
    ELSE=7,ELIF=8,DEF=9,RETURN=10,BREAK=11,CONTINUE=12,
    IMPORT=13,FROM=14,GLOBAL=15,AS=16,PASS=17,INTNUM=18,
    REALNUM=19,TRUE=20,FALSE=21,LPAR=22,RPAR=23,LBRACE=24,
    RBRACE=25,LBRACKET=26,RBRACKET=27,DOT=28,COMMA=29,COLON=30,
    SEMICOLON=31,INDENT=32,UNINDENT=33,ARROW=34,STRINGNUM=35,ASSIGN=36,
    PLUSEQUAL=37,MINUSEQUAL=38,STAREQUAL=39,DIVEQUAL=40,PLUS=41,MINUS=42,
    STAR=43,DIVIDE=44,SLASHSLASH=45,PERCENTAGE=46,ID=47,LESS=48,
    GREATER=49,LESSEQUAL=50,GREATEREQUAL=51,EQUAL=52,NOTEQUAL=53,AND=54,
    OR=55,NOT=56,STARSTAR=57};

public partial struct ValueType
{
	public expression ex;
	public ident id;
    public Object ob;
    public op_type_node op;
    public syntax_tree_node stn;
    public token_info ti;
    public type_definition td;
}
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public partial class SPythonGPPGParser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from SPythonParser.y
   	public syntax_tree_node root;
	public List<Error> errors;
    // public string current_file_name;
    // public int max_errors = 10;
	public SPythonParserTools parserTools;
    public List<compiler_directive> CompilerDirectives;
	public ParserLambdaHelper lambdaHelper = new ParserLambdaHelper();
	public bool is_unit_to_be_parsed = false;

	public SPythonGPPGParser(AbstractScanner<ValueType, LexLocation> scanner, SPythonParserTools parserTools,
	bool isUnitToBeParsed) : base(scanner) 
	{ 
		this.parserTools = parserTools;
		this.is_unit_to_be_parsed = isUnitToBeParsed;
	}
  // End verbatim content from SPythonParser.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[121];
  private static State[] states = new State[209];
  private static string[] nonTerms = new string[] {
      "ident", "dotted_ident", "func_name_ident", "expr", "proc_func_call", "const_value", 
      "variable", "optional_condition", "act_param", "act_param_list", "optional_act_param_list", 
      "proc_func_decl", "return_stmt", "break_stmt", "continue_stmt", "global_stmt", 
      "pass_stmt", "var_stmt", "assign_stmt", "if_stmt", "stmt", "proc_func_call_stmt", 
      "while_stmt", "for_stmt", "optional_else", "optional_elif", "import_or_decl_or_stmt", 
      "import_and_decl_and_stmt_list", "expr_list", "stmt_list", "block", "program", 
      "import_or_decl", "param_name", "form_param_sect", "form_param_list", "optional_form_param_list", 
      "dotted_ident_list", "ident_as_ident", "ident_as_ident_list", "proc_func_header", 
      "type_ref", "simple_type_identifier", "template_type", "import_clause", 
      "template_type_params", "template_param_list", "optional_semicolon", "assign_type", 
      "$accept", };

  static SPythonGPPGParser() {
    states[0] = new State(new int[]{47,62,18,67,19,68,20,69,21,70,35,71,26,72,6,121,5,142,3,147,10,154,11,157,12,159,15,161,17,170,9,176,13,195,14,203},new int[]{-32,1,-28,3,-27,208,-21,7,-19,8,-7,9,-1,61,-5,117,-6,118,-18,119,-20,120,-22,140,-23,141,-24,146,-13,153,-14,156,-15,158,-16,160,-17,169,-33,172,-12,173,-41,174,-45,194});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{31,5,2,-120},new int[]{-48,4});
    states[4] = new State(-2);
    states[5] = new State(new int[]{47,62,18,67,19,68,20,69,21,70,35,71,26,72,6,121,5,142,3,147,10,154,11,157,12,159,15,161,17,170,9,176,13,195,14,203,2,-119},new int[]{-27,6,-21,7,-19,8,-7,9,-1,61,-5,117,-6,118,-18,119,-20,120,-22,140,-23,141,-24,146,-13,153,-14,156,-15,158,-16,160,-17,169,-33,172,-12,173,-41,174,-45,194});
    states[6] = new State(-11);
    states[7] = new State(-6);
    states[8] = new State(-14);
    states[9] = new State(new int[]{36,10,22,51,28,90,26,92,30,97,37,113,38,114,39,115,40,116},new int[]{-49,95});
    states[10] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,11,-7,50,-1,61,-5,63,-6,64});
    states[11] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44,31,-38,2,-38});
    states[12] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,13,-7,50,-1,61,-5,63,-6,64});
    states[13] = new State(new int[]{7,14,6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44});
    states[14] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,15,-7,50,-1,61,-5,63,-6,64});
    states[15] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44,31,-44,2,-44,7,-44,29,-44,23,-44,3,-44,27,-44,30,-44});
    states[16] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,17,-7,50,-1,61,-5,63,-6,64});
    states[17] = new State(new int[]{6,12,41,-45,43,18,44,20,42,-45,48,-45,49,-45,50,-45,51,-45,52,-45,53,-45,54,-45,55,-45,45,40,46,42,57,44,31,-45,2,-45,7,-45,29,-45,23,-45,3,-45,27,-45,30,-45});
    states[18] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,19,-7,50,-1,61,-5,63,-6,64});
    states[19] = new State(new int[]{6,12,41,-46,43,-46,44,-46,42,-46,48,-46,49,-46,50,-46,51,-46,52,-46,53,-46,54,-46,55,-46,45,-46,46,-46,57,44,31,-46,2,-46,7,-46,29,-46,23,-46,3,-46,27,-46,30,-46});
    states[20] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,21,-7,50,-1,61,-5,63,-6,64});
    states[21] = new State(new int[]{6,12,41,-47,43,-47,44,-47,42,-47,48,-47,49,-47,50,-47,51,-47,52,-47,53,-47,54,-47,55,-47,45,-47,46,-47,57,44,31,-47,2,-47,7,-47,29,-47,23,-47,3,-47,27,-47,30,-47});
    states[22] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,23,-7,50,-1,61,-5,63,-6,64});
    states[23] = new State(new int[]{6,12,41,-48,43,18,44,20,42,-48,48,-48,49,-48,50,-48,51,-48,52,-48,53,-48,54,-48,55,-48,45,40,46,42,57,44,31,-48,2,-48,7,-48,29,-48,23,-48,3,-48,27,-48,30,-48});
    states[24] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,25,-7,50,-1,61,-5,63,-6,64});
    states[25] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,-49,49,-49,50,-49,51,-49,52,-49,53,-49,54,-49,55,-49,45,40,46,42,57,44,31,-49,2,-49,7,-49,29,-49,23,-49,3,-49,27,-49,30,-49});
    states[26] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,27,-7,50,-1,61,-5,63,-6,64});
    states[27] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,-50,49,-50,50,-50,51,-50,52,-50,53,-50,54,-50,55,-50,45,40,46,42,57,44,31,-50,2,-50,7,-50,29,-50,23,-50,3,-50,27,-50,30,-50});
    states[28] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,29,-7,50,-1,61,-5,63,-6,64});
    states[29] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,-51,49,-51,50,-51,51,-51,52,-51,53,-51,54,-51,55,-51,45,40,46,42,57,44,31,-51,2,-51,7,-51,29,-51,23,-51,3,-51,27,-51,30,-51});
    states[30] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,31,-7,50,-1,61,-5,63,-6,64});
    states[31] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,-52,49,-52,50,-52,51,-52,52,-52,53,-52,54,-52,55,-52,45,40,46,42,57,44,31,-52,2,-52,7,-52,29,-52,23,-52,3,-52,27,-52,30,-52});
    states[32] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,33,-7,50,-1,61,-5,63,-6,64});
    states[33] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,-53,49,-53,50,-53,51,-53,52,-53,53,-53,54,-53,55,-53,45,40,46,42,57,44,31,-53,2,-53,7,-53,29,-53,23,-53,3,-53,27,-53,30,-53});
    states[34] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,35,-7,50,-1,61,-5,63,-6,64});
    states[35] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,-54,49,-54,50,-54,51,-54,52,-54,53,-54,54,-54,55,-54,45,40,46,42,57,44,31,-54,2,-54,7,-54,29,-54,23,-54,3,-54,27,-54,30,-54});
    states[36] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,37,-7,50,-1,61,-5,63,-6,64});
    states[37] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,-55,55,-55,45,40,46,42,57,44,31,-55,2,-55,7,-55,29,-55,23,-55,3,-55,27,-55,30,-55});
    states[38] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,39,-7,50,-1,61,-5,63,-6,64});
    states[39] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,-56,45,40,46,42,57,44,31,-56,2,-56,7,-56,29,-56,23,-56,3,-56,27,-56,30,-56});
    states[40] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,41,-7,50,-1,61,-5,63,-6,64});
    states[41] = new State(new int[]{6,12,41,-57,43,-57,44,-57,42,-57,48,-57,49,-57,50,-57,51,-57,52,-57,53,-57,54,-57,55,-57,45,-57,46,-57,57,44,31,-57,2,-57,7,-57,29,-57,23,-57,3,-57,27,-57,30,-57});
    states[42] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,43,-7,50,-1,61,-5,63,-6,64});
    states[43] = new State(new int[]{6,12,41,-58,43,-58,44,-58,42,-58,48,-58,49,-58,50,-58,51,-58,52,-58,53,-58,54,-58,55,-58,45,-58,46,-58,57,44,31,-58,2,-58,7,-58,29,-58,23,-58,3,-58,27,-58,30,-58});
    states[44] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,45,-7,50,-1,61,-5,63,-6,64});
    states[45] = new State(new int[]{6,12,41,-59,43,-59,44,-59,42,-59,48,-59,49,-59,50,-59,51,-59,52,-59,53,-59,54,-59,55,-59,45,-59,46,-59,57,44,31,-59,2,-59,7,-59,29,-59,23,-59,3,-59,27,-59,30,-59});
    states[46] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,47,-7,50,-1,61,-5,63,-6,64});
    states[47] = new State(new int[]{6,12,41,-60,43,18,44,20,42,-60,48,-60,49,-60,50,-60,51,-60,52,-60,53,-60,54,-60,55,-60,45,40,46,42,57,44,31,-60,2,-60,7,-60,29,-60,23,-60,3,-60,27,-60,30,-60});
    states[48] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,49,-7,50,-1,61,-5,63,-6,64});
    states[49] = new State(new int[]{6,12,41,-61,43,-61,44,-61,42,-61,48,-61,49,-61,50,-61,51,-61,52,-61,53,-61,54,-61,55,-61,45,-61,46,-61,57,44,31,-61,2,-61,7,-61,29,-61,23,-61,3,-61,27,-61,30,-61});
    states[50] = new State(new int[]{22,51,28,90,26,92,6,-62,41,-62,43,-62,44,-62,42,-62,48,-62,49,-62,50,-62,51,-62,52,-62,53,-62,54,-62,55,-62,45,-62,46,-62,57,-62,31,-62,2,-62,7,-62,29,-62,23,-62,3,-62,27,-62,30,-62});
    states[51] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77,23,-118},new int[]{-11,52,-10,54,-9,89,-4,57,-7,50,-1,58,-5,63,-6,64});
    states[52] = new State(new int[]{23,53});
    states[53] = new State(-98);
    states[54] = new State(new int[]{29,55,23,-117});
    states[55] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-9,56,-4,57,-7,50,-1,58,-5,63,-6,64});
    states[56] = new State(-116);
    states[57] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44,29,-113,23,-113});
    states[58] = new State(new int[]{36,59,22,-85,28,-85,26,-85,6,-85,41,-85,43,-85,44,-85,42,-85,48,-85,49,-85,50,-85,51,-85,52,-85,53,-85,54,-85,55,-85,45,-85,46,-85,57,-85,29,-85,23,-85});
    states[59] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,60,-7,50,-1,61,-5,63,-6,64});
    states[60] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44,29,-114,23,-114});
    states[61] = new State(-85);
    states[62] = new State(-27);
    states[63] = new State(-86);
    states[64] = new State(new int[]{28,65,6,-63,41,-63,43,-63,44,-63,42,-63,48,-63,49,-63,50,-63,51,-63,52,-63,53,-63,54,-63,55,-63,45,-63,46,-63,57,-63,31,-63,2,-63,7,-63,29,-63,23,-63,3,-63,27,-63,30,-63});
    states[65] = new State(new int[]{47,62},new int[]{-1,66});
    states[66] = new State(-88);
    states[67] = new State(-65);
    states[68] = new State(-66);
    states[69] = new State(-67);
    states[70] = new State(-68);
    states[71] = new State(-69);
    states[72] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-29,73,-4,80,-7,50,-1,61,-5,63,-6,64});
    states[73] = new State(new int[]{27,74,29,75});
    states[74] = new State(-89);
    states[75] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,76,-7,50,-1,61,-5,63,-6,64});
    states[76] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44,27,-71,29,-71});
    states[77] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,78,-7,50,-1,61,-5,63,-6,64});
    states[78] = new State(new int[]{23,79,6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44});
    states[79] = new State(-64);
    states[80] = new State(new int[]{3,81,6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44,27,-70,29,-70});
    states[81] = new State(new int[]{47,62},new int[]{-1,82});
    states[82] = new State(new int[]{4,83});
    states[83] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,84,-7,50,-1,61,-5,63,-6,64});
    states[84] = new State(new int[]{6,87,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44,27,-92},new int[]{-8,85});
    states[85] = new State(new int[]{27,86});
    states[86] = new State(-91);
    states[87] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,88,-7,50,-1,61,-5,63,-6,64});
    states[88] = new State(new int[]{7,14,6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44,27,-93});
    states[89] = new State(-115);
    states[90] = new State(new int[]{47,62},new int[]{-1,91});
    states[91] = new State(-87);
    states[92] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,93,-7,50,-1,61,-5,63,-6,64});
    states[93] = new State(new int[]{27,94,6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44});
    states[94] = new State(-90);
    states[95] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,96,-7,50,-1,61,-5,63,-6,64});
    states[96] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44,31,-39,2,-39});
    states[97] = new State(new int[]{47,62},new int[]{-42,98,-43,101,-1,110,-44,111});
    states[98] = new State(new int[]{36,99,31,-36,2,-36});
    states[99] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,100,-7,50,-1,61,-5,63,-6,64});
    states[100] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44,31,-37,2,-37});
    states[101] = new State(new int[]{28,102,26,105,36,-101,31,-101,2,-101,27,-101,29,-101,30,-101,23,-101},new int[]{-46,104});
    states[102] = new State(new int[]{47,62},new int[]{-1,103});
    states[103] = new State(-100);
    states[104] = new State(-103);
    states[105] = new State(new int[]{47,62},new int[]{-47,106,-42,112,-43,101,-1,110,-44,111});
    states[106] = new State(new int[]{27,107,29,108});
    states[107] = new State(-104);
    states[108] = new State(new int[]{47,62},new int[]{-42,109,-43,101,-1,110,-44,111});
    states[109] = new State(-106);
    states[110] = new State(-99);
    states[111] = new State(-102);
    states[112] = new State(-105);
    states[113] = new State(-40);
    states[114] = new State(-41);
    states[115] = new State(-42);
    states[116] = new State(-43);
    states[117] = new State(new int[]{36,-86,22,-86,28,-86,26,-86,30,-86,37,-86,38,-86,39,-86,40,-86,31,-84,2,-84});
    states[118] = new State(new int[]{28,65});
    states[119] = new State(-15);
    states[120] = new State(-16);
    states[121] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,122,-7,50,-1,61,-5,63,-6,64});
    states[122] = new State(new int[]{30,123,6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44});
    states[123] = new State(new int[]{32,135},new int[]{-31,124});
    states[124] = new State(new int[]{8,126,7,132,31,-76,2,-76},new int[]{-26,125,-25,131});
    states[125] = new State(-72);
    states[126] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,127,-7,50,-1,61,-5,63,-6,64});
    states[127] = new State(new int[]{30,128,6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44});
    states[128] = new State(new int[]{32,135},new int[]{-31,129});
    states[129] = new State(new int[]{8,126,7,132,31,-76,2,-76},new int[]{-26,130,-25,131});
    states[130] = new State(-73);
    states[131] = new State(-74);
    states[132] = new State(new int[]{30,133});
    states[133] = new State(new int[]{32,135},new int[]{-31,134});
    states[134] = new State(-75);
    states[135] = new State(new int[]{47,62,18,67,19,68,20,69,21,70,35,71,26,72,6,121,5,142,3,147,10,154,11,157,12,159,15,161,17,170},new int[]{-30,136,-21,171,-19,8,-7,9,-1,61,-5,117,-6,118,-18,119,-20,120,-22,140,-23,141,-24,146,-13,153,-14,156,-15,158,-16,160,-17,169});
    states[136] = new State(new int[]{31,137});
    states[137] = new State(new int[]{33,138,47,62,18,67,19,68,20,69,21,70,35,71,26,72,6,121,5,142,3,147,10,154,11,157,12,159,15,161,17,170},new int[]{-21,139,-19,8,-7,9,-1,61,-5,117,-6,118,-18,119,-20,120,-22,140,-23,141,-24,146,-13,153,-14,156,-15,158,-16,160,-17,169});
    states[138] = new State(-94);
    states[139] = new State(-13);
    states[140] = new State(-17);
    states[141] = new State(-18);
    states[142] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,143,-7,50,-1,61,-5,63,-6,64});
    states[143] = new State(new int[]{30,144,6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44});
    states[144] = new State(new int[]{32,135},new int[]{-31,145});
    states[145] = new State(-77);
    states[146] = new State(-19);
    states[147] = new State(new int[]{47,62},new int[]{-1,148});
    states[148] = new State(new int[]{4,149});
    states[149] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77},new int[]{-4,150,-7,50,-1,61,-5,63,-6,64});
    states[150] = new State(new int[]{30,151,6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44});
    states[151] = new State(new int[]{32,135},new int[]{-31,152});
    states[152] = new State(-78);
    states[153] = new State(-20);
    states[154] = new State(new int[]{42,46,56,48,47,62,18,67,19,68,20,69,21,70,35,71,26,72,22,77,31,-81,2,-81},new int[]{-4,155,-7,50,-1,61,-5,63,-6,64});
    states[155] = new State(new int[]{6,12,41,16,43,18,44,20,42,22,48,24,49,26,50,28,51,30,52,32,53,34,54,36,55,38,45,40,46,42,57,44,31,-80,2,-80});
    states[156] = new State(-21);
    states[157] = new State(-82);
    states[158] = new State(-22);
    states[159] = new State(-83);
    states[160] = new State(-23);
    states[161] = new State(new int[]{47,62},new int[]{-38,162,-2,168,-1,167});
    states[162] = new State(new int[]{29,163,31,-26,2,-26});
    states[163] = new State(new int[]{47,62},new int[]{-2,164,-1,167});
    states[164] = new State(new int[]{28,165,29,-31,31,-31,2,-31});
    states[165] = new State(new int[]{47,62},new int[]{-1,166});
    states[166] = new State(-29);
    states[167] = new State(-28);
    states[168] = new State(new int[]{28,165,29,-30,31,-30,2,-30});
    states[169] = new State(-24);
    states[170] = new State(-25);
    states[171] = new State(-12);
    states[172] = new State(-7);
    states[173] = new State(-8);
    states[174] = new State(new int[]{32,135},new int[]{-31,175});
    states[175] = new State(-95);
    states[176] = new State(new int[]{47,62},new int[]{-3,177,-1,193});
    states[177] = new State(new int[]{22,178});
    states[178] = new State(new int[]{47,62,23,-112},new int[]{-37,179,-36,185,-35,192,-34,188,-1,191});
    states[179] = new State(new int[]{23,180});
    states[180] = new State(new int[]{30,181,34,182});
    states[181] = new State(-96);
    states[182] = new State(new int[]{47,62},new int[]{-42,183,-43,101,-1,110,-44,111});
    states[183] = new State(new int[]{30,184});
    states[184] = new State(-97);
    states[185] = new State(new int[]{29,186,23,-111});
    states[186] = new State(new int[]{47,62},new int[]{-35,187,-34,188,-1,191});
    states[187] = new State(-110);
    states[188] = new State(new int[]{30,189});
    states[189] = new State(new int[]{47,62},new int[]{-42,190,-43,101,-1,110,-44,111});
    states[190] = new State(-108);
    states[191] = new State(-107);
    states[192] = new State(-109);
    states[193] = new State(-79);
    states[194] = new State(-9);
    states[195] = new State(new int[]{47,62},new int[]{-40,196,-39,202,-1,199});
    states[196] = new State(new int[]{29,197,31,-3,2,-3});
    states[197] = new State(new int[]{47,62},new int[]{-39,198,-1,199});
    states[198] = new State(-35);
    states[199] = new State(new int[]{16,200,29,-33,31,-33,2,-33});
    states[200] = new State(new int[]{47,62},new int[]{-1,201});
    states[201] = new State(-32);
    states[202] = new State(-34);
    states[203] = new State(new int[]{47,62},new int[]{-1,204});
    states[204] = new State(new int[]{13,205});
    states[205] = new State(new int[]{43,207,47,62},new int[]{-40,206,-39,202,-1,199});
    states[206] = new State(new int[]{29,197,31,-4,2,-4});
    states[207] = new State(-5);
    states[208] = new State(-10);

    rules[1] = new Rule(-50, new int[]{-32,2});
    rules[2] = new Rule(-32, new int[]{-28,-48});
    rules[3] = new Rule(-45, new int[]{13,-40});
    rules[4] = new Rule(-45, new int[]{14,-1,13,-40});
    rules[5] = new Rule(-45, new int[]{14,-1,13,43});
    rules[6] = new Rule(-27, new int[]{-21});
    rules[7] = new Rule(-27, new int[]{-33});
    rules[8] = new Rule(-33, new int[]{-12});
    rules[9] = new Rule(-33, new int[]{-45});
    rules[10] = new Rule(-28, new int[]{-27});
    rules[11] = new Rule(-28, new int[]{-28,31,-27});
    rules[12] = new Rule(-30, new int[]{-21});
    rules[13] = new Rule(-30, new int[]{-30,31,-21});
    rules[14] = new Rule(-21, new int[]{-19});
    rules[15] = new Rule(-21, new int[]{-18});
    rules[16] = new Rule(-21, new int[]{-20});
    rules[17] = new Rule(-21, new int[]{-22});
    rules[18] = new Rule(-21, new int[]{-23});
    rules[19] = new Rule(-21, new int[]{-24});
    rules[20] = new Rule(-21, new int[]{-13});
    rules[21] = new Rule(-21, new int[]{-14});
    rules[22] = new Rule(-21, new int[]{-15});
    rules[23] = new Rule(-21, new int[]{-16});
    rules[24] = new Rule(-21, new int[]{-17});
    rules[25] = new Rule(-17, new int[]{17});
    rules[26] = new Rule(-16, new int[]{15,-38});
    rules[27] = new Rule(-1, new int[]{47});
    rules[28] = new Rule(-2, new int[]{-1});
    rules[29] = new Rule(-2, new int[]{-2,28,-1});
    rules[30] = new Rule(-38, new int[]{-2});
    rules[31] = new Rule(-38, new int[]{-38,29,-2});
    rules[32] = new Rule(-39, new int[]{-1,16,-1});
    rules[33] = new Rule(-39, new int[]{-1});
    rules[34] = new Rule(-40, new int[]{-39});
    rules[35] = new Rule(-40, new int[]{-40,29,-39});
    rules[36] = new Rule(-18, new int[]{-7,30,-42});
    rules[37] = new Rule(-18, new int[]{-7,30,-42,36,-4});
    rules[38] = new Rule(-19, new int[]{-7,36,-4});
    rules[39] = new Rule(-19, new int[]{-7,-49,-4});
    rules[40] = new Rule(-49, new int[]{37});
    rules[41] = new Rule(-49, new int[]{38});
    rules[42] = new Rule(-49, new int[]{39});
    rules[43] = new Rule(-49, new int[]{40});
    rules[44] = new Rule(-4, new int[]{-4,6,-4,7,-4});
    rules[45] = new Rule(-4, new int[]{-4,41,-4});
    rules[46] = new Rule(-4, new int[]{-4,43,-4});
    rules[47] = new Rule(-4, new int[]{-4,44,-4});
    rules[48] = new Rule(-4, new int[]{-4,42,-4});
    rules[49] = new Rule(-4, new int[]{-4,48,-4});
    rules[50] = new Rule(-4, new int[]{-4,49,-4});
    rules[51] = new Rule(-4, new int[]{-4,50,-4});
    rules[52] = new Rule(-4, new int[]{-4,51,-4});
    rules[53] = new Rule(-4, new int[]{-4,52,-4});
    rules[54] = new Rule(-4, new int[]{-4,53,-4});
    rules[55] = new Rule(-4, new int[]{-4,54,-4});
    rules[56] = new Rule(-4, new int[]{-4,55,-4});
    rules[57] = new Rule(-4, new int[]{-4,45,-4});
    rules[58] = new Rule(-4, new int[]{-4,46,-4});
    rules[59] = new Rule(-4, new int[]{-4,57,-4});
    rules[60] = new Rule(-4, new int[]{42,-4});
    rules[61] = new Rule(-4, new int[]{56,-4});
    rules[62] = new Rule(-4, new int[]{-7});
    rules[63] = new Rule(-4, new int[]{-6});
    rules[64] = new Rule(-4, new int[]{22,-4,23});
    rules[65] = new Rule(-6, new int[]{18});
    rules[66] = new Rule(-6, new int[]{19});
    rules[67] = new Rule(-6, new int[]{20});
    rules[68] = new Rule(-6, new int[]{21});
    rules[69] = new Rule(-6, new int[]{35});
    rules[70] = new Rule(-29, new int[]{-4});
    rules[71] = new Rule(-29, new int[]{-29,29,-4});
    rules[72] = new Rule(-20, new int[]{6,-4,30,-31,-26});
    rules[73] = new Rule(-26, new int[]{8,-4,30,-31,-26});
    rules[74] = new Rule(-26, new int[]{-25});
    rules[75] = new Rule(-25, new int[]{7,30,-31});
    rules[76] = new Rule(-25, new int[]{});
    rules[77] = new Rule(-23, new int[]{5,-4,30,-31});
    rules[78] = new Rule(-24, new int[]{3,-1,4,-4,30,-31});
    rules[79] = new Rule(-3, new int[]{-1});
    rules[80] = new Rule(-13, new int[]{10,-4});
    rules[81] = new Rule(-13, new int[]{10});
    rules[82] = new Rule(-14, new int[]{11});
    rules[83] = new Rule(-15, new int[]{12});
    rules[84] = new Rule(-22, new int[]{-5});
    rules[85] = new Rule(-7, new int[]{-1});
    rules[86] = new Rule(-7, new int[]{-5});
    rules[87] = new Rule(-7, new int[]{-7,28,-1});
    rules[88] = new Rule(-7, new int[]{-6,28,-1});
    rules[89] = new Rule(-7, new int[]{26,-29,27});
    rules[90] = new Rule(-7, new int[]{-7,26,-4,27});
    rules[91] = new Rule(-7, new int[]{26,-4,3,-1,4,-4,-8,27});
    rules[92] = new Rule(-8, new int[]{});
    rules[93] = new Rule(-8, new int[]{6,-4});
    rules[94] = new Rule(-31, new int[]{32,-30,31,33});
    rules[95] = new Rule(-12, new int[]{-41,-31});
    rules[96] = new Rule(-41, new int[]{9,-3,22,-37,23,30});
    rules[97] = new Rule(-41, new int[]{9,-3,22,-37,23,34,-42,30});
    rules[98] = new Rule(-5, new int[]{-7,22,-11,23});
    rules[99] = new Rule(-43, new int[]{-1});
    rules[100] = new Rule(-43, new int[]{-43,28,-1});
    rules[101] = new Rule(-42, new int[]{-43});
    rules[102] = new Rule(-42, new int[]{-44});
    rules[103] = new Rule(-44, new int[]{-43,-46});
    rules[104] = new Rule(-46, new int[]{26,-47,27});
    rules[105] = new Rule(-47, new int[]{-42});
    rules[106] = new Rule(-47, new int[]{-47,29,-42});
    rules[107] = new Rule(-34, new int[]{-1});
    rules[108] = new Rule(-35, new int[]{-34,30,-42});
    rules[109] = new Rule(-36, new int[]{-35});
    rules[110] = new Rule(-36, new int[]{-36,29,-35});
    rules[111] = new Rule(-37, new int[]{-36});
    rules[112] = new Rule(-37, new int[]{});
    rules[113] = new Rule(-9, new int[]{-4});
    rules[114] = new Rule(-9, new int[]{-1,36,-4});
    rules[115] = new Rule(-10, new int[]{-9});
    rules[116] = new Rule(-10, new int[]{-10,29,-9});
    rules[117] = new Rule(-11, new int[]{-10});
    rules[118] = new Rule(-11, new int[]{});
    rules[119] = new Rule(-48, new int[]{31});
    rules[120] = new Rule(-48, new int[]{});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // program -> import_and_decl_and_stmt_list, optional_semicolon
{
			// main program
			if (!is_unit_to_be_parsed) {
				var stl = ValueStack[ValueStack.Depth-2].stn as statement_list;
				stl.left_logical_bracket = new token_info("");
				stl.right_logical_bracket = new token_info("");
				var bl = new block(new declarations(), stl, CurrentLocationSpan);
				root = CurrentSemanticValue.stn = NewProgramModule(null, null, new uses_list(), bl, ValueStack[ValueStack.Depth-1].ob, CurrentLocationSpan);
				root.source_context = bl.source_context;
			}
			// unit
			else {
				var interface_part = new interface_node(new declarations(), new uses_list(), null, null);
				var initialization_part = new initfinal_part(null, ValueStack[ValueStack.Depth-2].stn as statement_list, null, null, null, CurrentLocationSpan);

				root = CurrentSemanticValue.stn = new unit_module(
					new unit_name(new ident(Path.GetFileNameWithoutExtension(parserTools.currentFileName)),
					UnitHeaderKeyword.Unit, CurrentLocationSpan), interface_part, null,
					initialization_part.initialization_sect,
					initialization_part.finalization_sect, null, CurrentLocationSpan);
			}

		}
        break;
      case 3: // import_clause -> IMPORT, ident_as_ident_list
{
			CurrentSemanticValue.stn = new import_statement(ValueStack[ValueStack.Depth-1].stn as as_statement_list, CurrentLocationSpan);
		}
        break;
      case 4: // import_clause -> FROM, ident, IMPORT, ident_as_ident_list
{
			CurrentSemanticValue.stn = new from_import_statement(ValueStack[ValueStack.Depth-3].id as ident, false, ValueStack[ValueStack.Depth-1].stn as as_statement_list, CurrentLocationSpan);
		}
        break;
      case 5: // import_clause -> FROM, ident, IMPORT, STAR
{
			CurrentSemanticValue.stn = new from_import_statement(ValueStack[ValueStack.Depth-3].id as ident, true, null, CurrentLocationSpan);
		}
        break;
      case 6: // import_or_decl_or_stmt -> stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 7: // import_or_decl_or_stmt -> import_or_decl
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 8: // import_or_decl -> proc_func_decl
{
			CurrentSemanticValue.stn = new declarations_as_statement(new declarations(ValueStack[ValueStack.Depth-1].stn as procedure_definition, CurrentLocationSpan), CurrentLocationSpan);
		}
        break;
      case 9: // import_or_decl -> import_clause
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn;
		}
        break;
      case 10: // import_and_decl_and_stmt_list -> import_or_decl_or_stmt
{
			CurrentSemanticValue.stn = new statement_list(ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 11: // import_and_decl_and_stmt_list -> import_and_decl_and_stmt_list, SEMICOLON, 
               //                                  import_or_decl_or_stmt
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as statement_list).Add(ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 12: // stmt_list -> stmt
{
			CurrentSemanticValue.stn = new statement_list(ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 13: // stmt_list -> stmt_list, SEMICOLON, stmt
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as statement_list).Add(ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 14: // stmt -> assign_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 15: // stmt -> var_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 16: // stmt -> if_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 17: // stmt -> proc_func_call_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 18: // stmt -> while_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 19: // stmt -> for_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 20: // stmt -> return_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 21: // stmt -> break_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 22: // stmt -> continue_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 23: // stmt -> global_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 24: // stmt -> pass_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 25: // pass_stmt -> PASS
{
			CurrentSemanticValue.stn = new empty_statement();
		}
        break;
      case 26: // global_stmt -> GLOBAL, dotted_ident_list
{
			CurrentSemanticValue.stn = new global_statement(ValueStack[ValueStack.Depth-1].stn as ident_list, CurrentLocationSpan);
		}
        break;
      case 27: // ident -> ID
{
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id;
		}
        break;
      case 28: // dotted_ident -> ident
{ 
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id; 
		}
        break;
      case 29: // dotted_ident -> dotted_ident, DOT, ident
{ 
			CurrentSemanticValue.id = new ident(ValueStack[ValueStack.Depth-3].id.name + "." + ValueStack[ValueStack.Depth-1].id.name, CurrentLocationSpan); 
		}
        break;
      case 30: // dotted_ident_list -> dotted_ident
{
			CurrentSemanticValue.stn = new ident_list(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 31: // dotted_ident_list -> dotted_ident_list, COMMA, dotted_ident
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as ident_list).Add(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 32: // ident_as_ident -> ident, AS, ident
{ 
			CurrentSemanticValue.stn = new as_statement(ValueStack[ValueStack.Depth-3].id, ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan); 
		}
        break;
      case 33: // ident_as_ident -> ident
{ 
			CurrentSemanticValue.stn = new as_statement(ValueStack[ValueStack.Depth-1].id, ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan); 
		}
        break;
      case 34: // ident_as_ident_list -> ident_as_ident
{
			CurrentSemanticValue.stn = new as_statement_list(ValueStack[ValueStack.Depth-1].stn as as_statement, CurrentLocationSpan);
		}
        break;
      case 35: // ident_as_ident_list -> ident_as_ident_list, COMMA, ident_as_ident
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as as_statement_list).Add(ValueStack[ValueStack.Depth-1].stn as as_statement, CurrentLocationSpan);
		}
        break;
      case 36: // var_stmt -> variable, COLON, type_ref
{
			var vds = new var_def_statement(new ident_list(ValueStack[ValueStack.Depth-3].ex as ident, LocationStack[LocationStack.Depth-3]), ValueStack[ValueStack.Depth-1].td, null, definition_attribute.None, false, CurrentLocationSpan);
			CurrentSemanticValue.stn = new var_statement(vds, CurrentLocationSpan);
		}
        break;
      case 37: // var_stmt -> variable, COLON, type_ref, ASSIGN, expr
{
			var vds = new var_def_statement(new ident_list(ValueStack[ValueStack.Depth-5].ex as ident, LocationStack[LocationStack.Depth-5]), ValueStack[ValueStack.Depth-3].td, ValueStack[ValueStack.Depth-1].ex, definition_attribute.None, false, CurrentLocationSpan);
			CurrentSemanticValue.stn = new var_statement(vds, CurrentLocationSpan);
		}
        break;
      case 38: // assign_stmt -> variable, ASSIGN, expr
{
			if (!(ValueStack[ValueStack.Depth-3].ex is addressed_value))
        		parserTools.AddErrorFromResource("LEFT_SIDE_CANNOT_BE_ASSIGNED_TO", CurrentLocationSpan);
			CurrentSemanticValue.stn = new assign(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan);
		}
        break;
      case 39: // assign_stmt -> variable, assign_type, expr
{
			if (!(ValueStack[ValueStack.Depth-3].ex is addressed_value))
        		parserTools.AddErrorFromResource("LEFT_SIDE_CANNOT_BE_ASSIGNED_TO", CurrentLocationSpan);
			CurrentSemanticValue.stn = new assign(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan);
		}
        break;
      case 40: // assign_type -> PLUSEQUAL
{ 
			CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; 
		}
        break;
      case 41: // assign_type -> MINUSEQUAL
{ 
			CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; 
		}
        break;
      case 42: // assign_type -> STAREQUAL
{ 
			CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; 
		}
        break;
      case 43: // assign_type -> DIVEQUAL
{ 
			CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; 
		}
        break;
      case 44: // expr -> expr, IF, expr, ELSE, expr
{
			CurrentSemanticValue.ex = new question_colon_expression(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-5].ex, ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 45: // expr -> expr, PLUS, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 46: // expr -> expr, STAR, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 47: // expr -> expr, DIVIDE, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 48: // expr -> expr, MINUS, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 49: // expr -> expr, LESS, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 50: // expr -> expr, GREATER, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 51: // expr -> expr, LESSEQUAL, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 52: // expr -> expr, GREATEREQUAL, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 53: // expr -> expr, EQUAL, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 54: // expr -> expr, NOTEQUAL, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 55: // expr -> expr, AND, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 56: // expr -> expr, OR, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 57: // expr -> expr, SLASHSLASH, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 58: // expr -> expr, PERCENTAGE, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 59: // expr -> expr, STARSTAR, expr
{
			addressed_value method_name = new ident("!pow", CurrentLocationSpan);
			expression_list el = new expression_list(new List<expression> { ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex }, CurrentLocationSpan);
			CurrentSemanticValue.ex = new method_call(method_name, el, CurrentLocationSpan);
		}
        break;
      case 60: // expr -> MINUS, expr
{ 
			CurrentSemanticValue.ex = new un_expr(ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 61: // expr -> NOT, expr
{ 
			CurrentSemanticValue.ex = new un_expr(ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 62: // expr -> variable
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 63: // expr -> const_value
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 64: // expr -> LPAR, expr, RPAR
{ 
			CurrentSemanticValue.ex = new bracket_expr(ValueStack[ValueStack.Depth-2].ex, CurrentLocationSpan); 
		}
        break;
      case 65: // const_value -> INTNUM
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 66: // const_value -> REALNUM
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 67: // const_value -> TRUE
{ 
			CurrentSemanticValue.ex = new ident("true", CurrentLocationSpan); 
		}
        break;
      case 68: // const_value -> FALSE
{ 
			CurrentSemanticValue.ex = new ident("false", CurrentLocationSpan); 
		}
        break;
      case 69: // const_value -> STRINGNUM
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].stn as literal; 
		}
        break;
      case 70: // expr_list -> expr
{
			CurrentSemanticValue.stn = new expression_list(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 71: // expr_list -> expr_list, COMMA, expr
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as expression_list).Add(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 72: // if_stmt -> IF, expr, COLON, block, optional_elif
{
			CurrentSemanticValue.stn = new if_node(ValueStack[ValueStack.Depth-4].ex, ValueStack[ValueStack.Depth-2].stn as statement, ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 73: // optional_elif -> ELIF, expr, COLON, block, optional_elif
{
			CurrentSemanticValue.stn = new if_node(ValueStack[ValueStack.Depth-4].ex, ValueStack[ValueStack.Depth-2].stn as statement, ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 74: // optional_elif -> optional_else
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 75: // optional_else -> ELSE, COLON, block
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 76: // optional_else -> /* empty */
{ 
			CurrentSemanticValue.stn = null; 
		}
        break;
      case 77: // while_stmt -> WHILE, expr, COLON, block
{
			CurrentSemanticValue.stn = new while_node(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].stn as statement, WhileCycleType.While, CurrentLocationSpan);
		}
        break;
      case 78: // for_stmt -> FOR, ident, IN, expr, COLON, block
{
			CurrentSemanticValue.stn = new foreach_stmt(ValueStack[ValueStack.Depth-5].id, new no_type_foreach(), ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].stn as statement, null, CurrentLocationSpan);
		}
        break;
      case 79: // func_name_ident -> ident
{
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id;
		}
        break;
      case 80: // return_stmt -> RETURN, expr
{
			statement res_assign = new assign(new ident("result"), ValueStack[ValueStack.Depth-1].ex, Operators.Assignment, CurrentLocationSpan);
			statement exit_call = new procedure_call(new ident("exit"), true, CurrentLocationSpan);
			CurrentSemanticValue.stn = new statement_list(res_assign, CurrentLocationSpan);
			(CurrentSemanticValue.stn as statement_list).Add(exit_call, CurrentLocationSpan);
		}
        break;
      case 81: // return_stmt -> RETURN
{
			CurrentSemanticValue.stn = new procedure_call(new ident("exit", CurrentLocationSpan), true, CurrentLocationSpan);
		}
        break;
      case 82: // break_stmt -> BREAK
{
			CurrentSemanticValue.stn = new procedure_call(new ident("break", CurrentLocationSpan), true, CurrentLocationSpan);
		}
        break;
      case 83: // continue_stmt -> CONTINUE
{
			CurrentSemanticValue.stn = new procedure_call(new ident("continue", CurrentLocationSpan), true, CurrentLocationSpan);
		}
        break;
      case 84: // proc_func_call_stmt -> proc_func_call
{
			CurrentSemanticValue.stn = new procedure_call(ValueStack[ValueStack.Depth-1].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex is ident, CurrentLocationSpan);
		}
        break;
      case 85: // variable -> ident
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].id; 
		}
        break;
      case 86: // variable -> proc_func_call
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 87: // variable -> variable, DOT, ident
{ 
			CurrentSemanticValue.ex = new dot_node(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].id as addressed_value, CurrentLocationSpan); 
		}
        break;
      case 88: // variable -> const_value, DOT, ident
{ 
			CurrentSemanticValue.ex = new dot_node(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].id as addressed_value, CurrentLocationSpan); 
		}
        break;
      case 89: // variable -> LBRACKET, expr_list, RBRACKET
{
			var acn = new array_const_new(ValueStack[ValueStack.Depth-2].stn as expression_list, '|', CurrentLocationSpan);
			var dn = new dot_node(acn as addressed_value, (new ident("ToList", CurrentLocationSpan)) as addressed_value, CurrentLocationSpan);
			CurrentSemanticValue.ex = new method_call(dn as addressed_value, null, CurrentLocationSpan);
		}
        break;
      case 90: // variable -> variable, LBRACKET, expr, RBRACKET
{
			var el = new expression_list(ValueStack[ValueStack.Depth-2].ex as expression, CurrentLocationSpan);
			CurrentSemanticValue.ex = new indexer(ValueStack[ValueStack.Depth-4].ex as addressed_value, el, CurrentLocationSpan);
		}
        break;
      case 91: // variable -> LBRACKET, expr, FOR, ident, IN, expr, optional_condition, RBRACKET
{
			CurrentSemanticValue.ex = new list_generator(ValueStack[ValueStack.Depth-7].ex, ValueStack[ValueStack.Depth-5].id, ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-2].ex, CurrentLocationSpan);
		}
        break;
      case 92: // optional_condition -> /* empty */
{ 
			CurrentSemanticValue.ex = null; 
		}
        break;
      case 93: // optional_condition -> IF, expr
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 94: // block -> INDENT, stmt_list, SEMICOLON, UNINDENT
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-3].stn as statement_list;
			(CurrentSemanticValue.stn as statement_list).left_logical_bracket = ValueStack[ValueStack.Depth-4].ti;
			(CurrentSemanticValue.stn as statement_list).right_logical_bracket = ValueStack[ValueStack.Depth-1].ti;
			CurrentSemanticValue.stn.source_context = LexLocation.MergeAll(LocationStack[LocationStack.Depth-3], LocationStack[LocationStack.Depth-2]);
		}
        break;
      case 95: // proc_func_decl -> proc_func_header, block
{
			CurrentSemanticValue.stn = new procedure_definition(ValueStack[ValueStack.Depth-2].td as procedure_header, new block(null, ValueStack[ValueStack.Depth-1].stn as statement_list, LocationStack[LocationStack.Depth-1]), CurrentLocationSpan);
		}
        break;
      case 96: // proc_func_header -> DEF, func_name_ident, LPAR, optional_form_param_list, RPAR, 
               //                     COLON
{
			CurrentSemanticValue.td = new procedure_header(ValueStack[ValueStack.Depth-3].stn as formal_parameters, new procedure_attributes_list(new List<procedure_attribute>()), new method_name(null,null, ValueStack[ValueStack.Depth-5].id, null, LocationStack[LocationStack.Depth-5]), null, CurrentLocationSpan);
		}
        break;
      case 97: // proc_func_header -> DEF, func_name_ident, LPAR, optional_form_param_list, RPAR, 
               //                     ARROW, type_ref, COLON
{
			CurrentSemanticValue.td = new function_header(ValueStack[ValueStack.Depth-5].stn as formal_parameters, new procedure_attributes_list(new List<procedure_attribute>()), new method_name(null,null, ValueStack[ValueStack.Depth-7].id, null, LocationStack[LocationStack.Depth-7]), null, ValueStack[ValueStack.Depth-2].td as type_definition, CurrentLocationSpan);
		}
        break;
      case 98: // proc_func_call -> variable, LPAR, optional_act_param_list, RPAR
{
			CurrentSemanticValue.ex = new method_call(ValueStack[ValueStack.Depth-4].ex as addressed_value, ValueStack[ValueStack.Depth-2].stn as expression_list, CurrentLocationSpan);
		}
        break;
      case 99: // simple_type_identifier -> ident
{
			CurrentSemanticValue.td = new named_type_reference(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 100: // simple_type_identifier -> simple_type_identifier, DOT, ident
{ 
			CurrentSemanticValue.td = (ValueStack[ValueStack.Depth-3].td as named_type_reference).Add(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 101: // type_ref -> simple_type_identifier
{
			CurrentSemanticValue.td = ValueStack[ValueStack.Depth-1].td as named_type_reference;
		}
        break;
      case 102: // type_ref -> template_type
{ 
			CurrentSemanticValue.td = ValueStack[ValueStack.Depth-1].td; 
		}
        break;
      case 103: // template_type -> simple_type_identifier, template_type_params
{ 
			CurrentSemanticValue.td = new template_type_reference(ValueStack[ValueStack.Depth-2].td as named_type_reference, ValueStack[ValueStack.Depth-1].stn as template_param_list, CurrentLocationSpan); 
		}
        break;
      case 104: // template_type_params -> LBRACKET, template_param_list, RBRACKET
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-2].stn;
			CurrentSemanticValue.stn.source_context = CurrentLocationSpan;
		}
        break;
      case 105: // template_param_list -> type_ref
{ 
			CurrentSemanticValue.stn = new template_param_list(ValueStack[ValueStack.Depth-1].td, CurrentLocationSpan);
		}
        break;
      case 106: // template_param_list -> template_param_list, COMMA, type_ref
{ 
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as template_param_list).Add(ValueStack[ValueStack.Depth-1].td, CurrentLocationSpan);
		}
        break;
      case 107: // param_name -> ident
{
			CurrentSemanticValue.stn = new ident_list(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 108: // form_param_sect -> param_name, COLON, type_ref
{
			CurrentSemanticValue.stn = new typed_parameters(ValueStack[ValueStack.Depth-3].stn as ident_list, ValueStack[ValueStack.Depth-1].td, parametr_kind.none, null, CurrentLocationSpan);
		}
        break;
      case 109: // form_param_list -> form_param_sect
{
			CurrentSemanticValue.stn = new formal_parameters(ValueStack[ValueStack.Depth-1].stn as typed_parameters, CurrentLocationSpan);
        }
        break;
      case 110: // form_param_list -> form_param_list, COMMA, form_param_sect
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as formal_parameters).Add(ValueStack[ValueStack.Depth-1].stn as typed_parameters, CurrentLocationSpan);
        }
        break;
      case 111: // optional_form_param_list -> form_param_list
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn;
		}
        break;
      case 112: // optional_form_param_list -> /* empty */
{
			CurrentSemanticValue.stn = null;
		}
        break;
      case 113: // act_param -> expr
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 114: // act_param -> ident, ASSIGN, expr
{ 
			CurrentSemanticValue.ex = new name_assign_expr(ValueStack[ValueStack.Depth-3].id, ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan); 
		}
        break;
      case 115: // act_param_list -> act_param
{
			CurrentSemanticValue.stn = new expression_list(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 116: // act_param_list -> act_param_list, COMMA, act_param
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as expression_list).Add(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 117: // optional_act_param_list -> act_param_list
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn;
		}
        break;
      case 118: // optional_act_param_list -> /* empty */
{
			CurrentSemanticValue.stn = null;
		}
        break;
      case 119: // optional_semicolon -> SEMICOLON
{ 
			CurrentSemanticValue.ob = ValueStack[ValueStack.Depth-1].ti; 
		}
        break;
      case 120: // optional_semicolon -> /* empty */
{ 
			CurrentSemanticValue.ob = null; 
		}
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


        public program_module NewProgramModule(program_name progName, Object optHeadCompDirs, uses_list mainUsesClose, syntax_tree_node progBlock, Object optPoint, LexLocation loc)
        {
            var progModule = new program_module(progName, mainUsesClose, progBlock as block, null, loc);
            progModule.Language = "Spython";
            if (optPoint == null && progBlock != null)
            {
                var fp = progBlock.source_context.end_position;
                var err_stn = progBlock;
			    if ((progBlock is block) && (progBlock as block).program_code != null && (progBlock as block).program_code.subnodes != null && (progBlock as block).program_code.subnodes.Count > 0)
                    err_stn = (progBlock as block).program_code.subnodes[(progBlock as block).program_code.subnodes.Count - 1];
                //parserTools.errors.Add(new SPythonUnexpectedToken(parserTools.currentFileName, StringResources.Get("TKPOINT"), new SourceContext(fp.line_num, fp.column_num + 1, fp.line_num, fp.column_num + 1, 0, 0), err_stn));
            }
            return progModule;
        }
}
}
