// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  DESKTOP-56159VE
// DateTime: 17.03.2025 20:08:04
// UserName: ????
// Input file <SPythonParser.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using PascalABCCompiler.SyntaxTree;
using PascalABCCompiler.ParserTools;
using PascalABCCompiler.Errors;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using SPythonParser;

namespace SPythonParserYacc
{
public enum Tokens {
    error=1,EOF=2,FOR=3,IN=4,WHILE=5,IF=6,
    ELSE=7,ELIF=8,DEF=9,RETURN=10,BREAK=11,CONTINUE=12,
    IMPORT=13,FROM=14,GLOBAL=15,AS=16,PASS=17,CLASS=18,
    LAMBDA=19,INDENT=20,UNINDENT=21,END_OF_FILE=22,END_OF_LINE=23,INTNUM=24,
    REALNUM=25,TRUE=26,FALSE=27,LPAR=28,RPAR=29,LBRACE=30,
    RBRACE=31,LBRACKET=32,RBRACKET=33,DOT=34,COMMA=35,COLON=36,
    SEMICOLON=37,ARROW=38,STRINGNUM=39,ASSIGN=40,PLUSEQUAL=41,MINUSEQUAL=42,
    STAREQUAL=43,DIVEQUAL=44,PLUS=45,MINUS=46,STAR=47,DIVIDE=48,
    SLASHSLASH=49,PERCENTAGE=50,ID=51,LESS=52,GREATER=53,LESSEQUAL=54,
    GREATEREQUAL=55,EQUAL=56,NOTEQUAL=57,AND=58,OR=59,NOT=60,
    STARSTAR=61};

public partial struct ValueType
{
	public expression ex;
	public ident id;
    public Object ob;
    public op_type_node op;
    public syntax_tree_node stn;
    public token_info ti;
    public type_definition td;
}
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public partial class SPythonGPPGParser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from SPythonParser.y
   	public syntax_tree_node root;
	public List<Error> errors;
    // public string current_file_name;
    // public int max_errors = 10;
	public SPythonParserTools parserTools;
    public List<compiler_directive> CompilerDirectives;
	public ParserLambdaHelper lambdaHelper = new ParserLambdaHelper();
	public bool is_unit_to_be_parsed = false;

	public SPythonGPPGParser(AbstractScanner<ValueType, LexLocation> scanner, SPythonParserTools parserTools,
	bool isUnitToBeParsed) : base(scanner) 
	{ 
		this.parserTools = parserTools;
		this.is_unit_to_be_parsed = isUnitToBeParsed;
	}
  // End verbatim content from SPythonParser.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[119];
  private static State[] states = new State[209];
  private static string[] nonTerms = new string[] {
      "ident", "dotted_ident", "func_name_ident", "expr", "proc_func_call", "const_value", 
      "variable", "optional_condition", "act_param", "act_param_list", "optional_act_param_list", 
      "proc_func_decl", "return_stmt", "break_stmt", "continue_stmt", "global_stmt", 
      "pass_stmt", "var_stmt", "assign_stmt", "if_stmt", "stmt", "proc_func_call_stmt", 
      "while_stmt", "for_stmt", "optional_else", "optional_elif", "expr_list", 
      "stmt_list", "block", "program", "param_name", "form_param_sect", "form_param_list", 
      "optional_form_param_list", "dotted_ident_list", "ident_as_ident", "ident_as_ident_list", 
      "proc_func_header", "type_ref", "simple_type_identifier", "template_type", 
      "import_clause", "template_type_params", "template_param_list", "optional_semicolon", 
      "end_of_line", "assign_type", "$accept", };

  static SPythonGPPGParser() {
    states[0] = new State(new int[]{51,62,24,67,25,68,26,69,27,70,39,71,32,72,6,121,5,141,3,146,10,153,11,156,12,158,15,160,17,169,9,173,13,192,14,200},new int[]{-30,1,-28,3,-21,207,-19,8,-7,9,-1,61,-5,117,-6,118,-18,119,-20,120,-22,139,-23,140,-24,145,-13,152,-14,155,-15,157,-16,159,-17,168,-12,170,-38,171,-42,191});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{37,208,23,205,22,-118},new int[]{-45,4,-46,6});
    states[4] = new State(new int[]{22,5});
    states[5] = new State(-2);
    states[6] = new State(new int[]{51,62,24,67,25,68,26,69,27,70,39,71,32,72,6,121,5,141,3,146,10,153,11,156,12,158,15,160,17,169,9,173,13,192,14,200},new int[]{-21,7,-19,8,-7,9,-1,61,-5,117,-6,118,-18,119,-20,120,-22,139,-23,140,-24,145,-13,152,-14,155,-15,157,-16,159,-17,168,-12,170,-38,171,-42,191});
    states[7] = new State(-4);
    states[8] = new State(-5);
    states[9] = new State(new int[]{40,10,28,51,34,90,32,92,36,97,41,113,42,114,43,115,44,116},new int[]{-47,95});
    states[10] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,11,-7,50,-1,61,-5,63,-6,64});
    states[11] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44,37,-34,23,-34,22,-34});
    states[12] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,13,-7,50,-1,61,-5,63,-6,64});
    states[13] = new State(new int[]{7,14,6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44});
    states[14] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,15,-7,50,-1,61,-5,63,-6,64});
    states[15] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44,37,-40,23,-40,22,-40,7,-40,35,-40,29,-40,3,-40,33,-40,36,-40});
    states[16] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,17,-7,50,-1,61,-5,63,-6,64});
    states[17] = new State(new int[]{6,12,45,-41,47,18,48,20,46,-41,52,-41,53,-41,54,-41,55,-41,56,-41,57,-41,58,-41,59,-41,49,40,50,42,61,44,37,-41,23,-41,22,-41,7,-41,35,-41,29,-41,3,-41,33,-41,36,-41});
    states[18] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,19,-7,50,-1,61,-5,63,-6,64});
    states[19] = new State(new int[]{6,12,45,-42,47,-42,48,-42,46,-42,52,-42,53,-42,54,-42,55,-42,56,-42,57,-42,58,-42,59,-42,49,-42,50,-42,61,44,37,-42,23,-42,22,-42,7,-42,35,-42,29,-42,3,-42,33,-42,36,-42});
    states[20] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,21,-7,50,-1,61,-5,63,-6,64});
    states[21] = new State(new int[]{6,12,45,-43,47,-43,48,-43,46,-43,52,-43,53,-43,54,-43,55,-43,56,-43,57,-43,58,-43,59,-43,49,-43,50,-43,61,44,37,-43,23,-43,22,-43,7,-43,35,-43,29,-43,3,-43,33,-43,36,-43});
    states[22] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,23,-7,50,-1,61,-5,63,-6,64});
    states[23] = new State(new int[]{6,12,45,-44,47,18,48,20,46,-44,52,-44,53,-44,54,-44,55,-44,56,-44,57,-44,58,-44,59,-44,49,40,50,42,61,44,37,-44,23,-44,22,-44,7,-44,35,-44,29,-44,3,-44,33,-44,36,-44});
    states[24] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,25,-7,50,-1,61,-5,63,-6,64});
    states[25] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,-45,53,-45,54,-45,55,-45,56,-45,57,-45,58,-45,59,-45,49,40,50,42,61,44,37,-45,23,-45,22,-45,7,-45,35,-45,29,-45,3,-45,33,-45,36,-45});
    states[26] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,27,-7,50,-1,61,-5,63,-6,64});
    states[27] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,-46,53,-46,54,-46,55,-46,56,-46,57,-46,58,-46,59,-46,49,40,50,42,61,44,37,-46,23,-46,22,-46,7,-46,35,-46,29,-46,3,-46,33,-46,36,-46});
    states[28] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,29,-7,50,-1,61,-5,63,-6,64});
    states[29] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,-47,53,-47,54,-47,55,-47,56,-47,57,-47,58,-47,59,-47,49,40,50,42,61,44,37,-47,23,-47,22,-47,7,-47,35,-47,29,-47,3,-47,33,-47,36,-47});
    states[30] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,31,-7,50,-1,61,-5,63,-6,64});
    states[31] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,-48,53,-48,54,-48,55,-48,56,-48,57,-48,58,-48,59,-48,49,40,50,42,61,44,37,-48,23,-48,22,-48,7,-48,35,-48,29,-48,3,-48,33,-48,36,-48});
    states[32] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,33,-7,50,-1,61,-5,63,-6,64});
    states[33] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,-49,53,-49,54,-49,55,-49,56,-49,57,-49,58,-49,59,-49,49,40,50,42,61,44,37,-49,23,-49,22,-49,7,-49,35,-49,29,-49,3,-49,33,-49,36,-49});
    states[34] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,35,-7,50,-1,61,-5,63,-6,64});
    states[35] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,-50,53,-50,54,-50,55,-50,56,-50,57,-50,58,-50,59,-50,49,40,50,42,61,44,37,-50,23,-50,22,-50,7,-50,35,-50,29,-50,3,-50,33,-50,36,-50});
    states[36] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,37,-7,50,-1,61,-5,63,-6,64});
    states[37] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,-51,59,-51,49,40,50,42,61,44,37,-51,23,-51,22,-51,7,-51,35,-51,29,-51,3,-51,33,-51,36,-51});
    states[38] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,39,-7,50,-1,61,-5,63,-6,64});
    states[39] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,-52,49,40,50,42,61,44,37,-52,23,-52,22,-52,7,-52,35,-52,29,-52,3,-52,33,-52,36,-52});
    states[40] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,41,-7,50,-1,61,-5,63,-6,64});
    states[41] = new State(new int[]{6,12,45,-53,47,-53,48,-53,46,-53,52,-53,53,-53,54,-53,55,-53,56,-53,57,-53,58,-53,59,-53,49,-53,50,-53,61,44,37,-53,23,-53,22,-53,7,-53,35,-53,29,-53,3,-53,33,-53,36,-53});
    states[42] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,43,-7,50,-1,61,-5,63,-6,64});
    states[43] = new State(new int[]{6,12,45,-54,47,-54,48,-54,46,-54,52,-54,53,-54,54,-54,55,-54,56,-54,57,-54,58,-54,59,-54,49,-54,50,-54,61,44,37,-54,23,-54,22,-54,7,-54,35,-54,29,-54,3,-54,33,-54,36,-54});
    states[44] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,45,-7,50,-1,61,-5,63,-6,64});
    states[45] = new State(new int[]{6,12,45,-55,47,-55,48,-55,46,-55,52,-55,53,-55,54,-55,55,-55,56,-55,57,-55,58,-55,59,-55,49,-55,50,-55,61,44,37,-55,23,-55,22,-55,7,-55,35,-55,29,-55,3,-55,33,-55,36,-55});
    states[46] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,47,-7,50,-1,61,-5,63,-6,64});
    states[47] = new State(new int[]{6,12,45,-56,47,18,48,20,46,-56,52,-56,53,-56,54,-56,55,-56,56,-56,57,-56,58,-56,59,-56,49,40,50,42,61,44,37,-56,23,-56,22,-56,7,-56,35,-56,29,-56,3,-56,33,-56,36,-56});
    states[48] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,49,-7,50,-1,61,-5,63,-6,64});
    states[49] = new State(new int[]{6,12,45,-57,47,-57,48,-57,46,-57,52,-57,53,-57,54,-57,55,-57,56,-57,57,-57,58,-57,59,-57,49,-57,50,-57,61,44,37,-57,23,-57,22,-57,7,-57,35,-57,29,-57,3,-57,33,-57,36,-57});
    states[50] = new State(new int[]{28,51,34,90,32,92,6,-58,45,-58,47,-58,48,-58,46,-58,52,-58,53,-58,54,-58,55,-58,56,-58,57,-58,58,-58,59,-58,49,-58,50,-58,61,-58,37,-58,23,-58,22,-58,7,-58,35,-58,29,-58,3,-58,33,-58,36,-58});
    states[51] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77,29,-114},new int[]{-11,52,-10,54,-9,89,-4,57,-7,50,-1,58,-5,63,-6,64});
    states[52] = new State(new int[]{29,53});
    states[53] = new State(-94);
    states[54] = new State(new int[]{35,55,29,-113});
    states[55] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-9,56,-4,57,-7,50,-1,58,-5,63,-6,64});
    states[56] = new State(-112);
    states[57] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44,35,-109,29,-109});
    states[58] = new State(new int[]{40,59,28,-81,34,-81,32,-81,6,-81,45,-81,47,-81,48,-81,46,-81,52,-81,53,-81,54,-81,55,-81,56,-81,57,-81,58,-81,59,-81,49,-81,50,-81,61,-81,35,-81,29,-81});
    states[59] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,60,-7,50,-1,61,-5,63,-6,64});
    states[60] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44,35,-110,29,-110});
    states[61] = new State(-81);
    states[62] = new State(-23);
    states[63] = new State(-82);
    states[64] = new State(new int[]{34,65,6,-59,45,-59,47,-59,48,-59,46,-59,52,-59,53,-59,54,-59,55,-59,56,-59,57,-59,58,-59,59,-59,49,-59,50,-59,61,-59,37,-59,23,-59,22,-59,7,-59,35,-59,29,-59,3,-59,33,-59,36,-59});
    states[65] = new State(new int[]{51,62},new int[]{-1,66});
    states[66] = new State(-84);
    states[67] = new State(-61);
    states[68] = new State(-62);
    states[69] = new State(-63);
    states[70] = new State(-64);
    states[71] = new State(-65);
    states[72] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-27,73,-4,80,-7,50,-1,61,-5,63,-6,64});
    states[73] = new State(new int[]{33,74,35,75});
    states[74] = new State(-85);
    states[75] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,76,-7,50,-1,61,-5,63,-6,64});
    states[76] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44,33,-67,35,-67});
    states[77] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,78,-7,50,-1,61,-5,63,-6,64});
    states[78] = new State(new int[]{29,79,6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44});
    states[79] = new State(-60);
    states[80] = new State(new int[]{3,81,6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44,33,-66,35,-66});
    states[81] = new State(new int[]{51,62},new int[]{-1,82});
    states[82] = new State(new int[]{4,83});
    states[83] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,84,-7,50,-1,61,-5,63,-6,64});
    states[84] = new State(new int[]{6,87,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44,33,-88},new int[]{-8,85});
    states[85] = new State(new int[]{33,86});
    states[86] = new State(-87);
    states[87] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,88,-7,50,-1,61,-5,63,-6,64});
    states[88] = new State(new int[]{7,14,6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44,33,-89});
    states[89] = new State(-111);
    states[90] = new State(new int[]{51,62},new int[]{-1,91});
    states[91] = new State(-83);
    states[92] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,93,-7,50,-1,61,-5,63,-6,64});
    states[93] = new State(new int[]{33,94,6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44});
    states[94] = new State(-86);
    states[95] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,96,-7,50,-1,61,-5,63,-6,64});
    states[96] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44,37,-35,23,-35,22,-35});
    states[97] = new State(new int[]{51,62},new int[]{-39,98,-40,101,-1,110,-41,111});
    states[98] = new State(new int[]{40,99,37,-32,23,-32,22,-32});
    states[99] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,100,-7,50,-1,61,-5,63,-6,64});
    states[100] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44,37,-33,23,-33,22,-33});
    states[101] = new State(new int[]{34,102,32,105,40,-97,37,-97,23,-97,22,-97,33,-97,35,-97,36,-97,29,-97},new int[]{-43,104});
    states[102] = new State(new int[]{51,62},new int[]{-1,103});
    states[103] = new State(-96);
    states[104] = new State(-99);
    states[105] = new State(new int[]{51,62},new int[]{-44,106,-39,112,-40,101,-1,110,-41,111});
    states[106] = new State(new int[]{33,107,35,108});
    states[107] = new State(-100);
    states[108] = new State(new int[]{51,62},new int[]{-39,109,-40,101,-1,110,-41,111});
    states[109] = new State(-102);
    states[110] = new State(-95);
    states[111] = new State(-98);
    states[112] = new State(-101);
    states[113] = new State(-36);
    states[114] = new State(-37);
    states[115] = new State(-38);
    states[116] = new State(-39);
    states[117] = new State(new int[]{40,-82,28,-82,34,-82,32,-82,36,-82,41,-82,42,-82,43,-82,44,-82,37,-80,23,-80,22,-80});
    states[118] = new State(new int[]{34,65});
    states[119] = new State(-6);
    states[120] = new State(-7);
    states[121] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,122,-7,50,-1,61,-5,63,-6,64});
    states[122] = new State(new int[]{36,123,6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44});
    states[123] = new State(new int[]{20,135},new int[]{-29,124});
    states[124] = new State(new int[]{8,126,7,132,37,-72,23,-72,22,-72},new int[]{-26,125,-25,131});
    states[125] = new State(-68);
    states[126] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,127,-7,50,-1,61,-5,63,-6,64});
    states[127] = new State(new int[]{36,128,6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44});
    states[128] = new State(new int[]{20,135},new int[]{-29,129});
    states[129] = new State(new int[]{8,126,7,132,37,-72,23,-72,22,-72},new int[]{-26,130,-25,131});
    states[130] = new State(-69);
    states[131] = new State(-70);
    states[132] = new State(new int[]{36,133});
    states[133] = new State(new int[]{20,135},new int[]{-29,134});
    states[134] = new State(-71);
    states[135] = new State(new int[]{51,62,24,67,25,68,26,69,27,70,39,71,32,72,6,121,5,141,3,146,10,153,11,156,12,158,15,160,17,169,9,173,13,192,14,200},new int[]{-28,136,-21,207,-19,8,-7,9,-1,61,-5,117,-6,118,-18,119,-20,120,-22,139,-23,140,-24,145,-13,152,-14,155,-15,157,-16,159,-17,168,-12,170,-38,171,-42,191});
    states[136] = new State(new int[]{23,205,37,206},new int[]{-46,137});
    states[137] = new State(new int[]{21,138,51,62,24,67,25,68,26,69,27,70,39,71,32,72,6,121,5,141,3,146,10,153,11,156,12,158,15,160,17,169,9,173,13,192,14,200},new int[]{-21,7,-19,8,-7,9,-1,61,-5,117,-6,118,-18,119,-20,120,-22,139,-23,140,-24,145,-13,152,-14,155,-15,157,-16,159,-17,168,-12,170,-38,171,-42,191});
    states[138] = new State(-90);
    states[139] = new State(-8);
    states[140] = new State(-9);
    states[141] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,142,-7,50,-1,61,-5,63,-6,64});
    states[142] = new State(new int[]{36,143,6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44});
    states[143] = new State(new int[]{20,135},new int[]{-29,144});
    states[144] = new State(-73);
    states[145] = new State(-10);
    states[146] = new State(new int[]{51,62},new int[]{-1,147});
    states[147] = new State(new int[]{4,148});
    states[148] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77},new int[]{-4,149,-7,50,-1,61,-5,63,-6,64});
    states[149] = new State(new int[]{36,150,6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44});
    states[150] = new State(new int[]{20,135},new int[]{-29,151});
    states[151] = new State(-74);
    states[152] = new State(-11);
    states[153] = new State(new int[]{46,46,60,48,51,62,24,67,25,68,26,69,27,70,39,71,32,72,28,77,37,-77,23,-77,22,-77},new int[]{-4,154,-7,50,-1,61,-5,63,-6,64});
    states[154] = new State(new int[]{6,12,45,16,47,18,48,20,46,22,52,24,53,26,54,28,55,30,56,32,57,34,58,36,59,38,49,40,50,42,61,44,37,-76,23,-76,22,-76});
    states[155] = new State(-12);
    states[156] = new State(-78);
    states[157] = new State(-13);
    states[158] = new State(-79);
    states[159] = new State(-14);
    states[160] = new State(new int[]{51,62},new int[]{-35,161,-2,167,-1,166});
    states[161] = new State(new int[]{35,162,37,-22,23,-22,22,-22});
    states[162] = new State(new int[]{51,62},new int[]{-2,163,-1,166});
    states[163] = new State(new int[]{34,164,35,-27,37,-27,23,-27,22,-27});
    states[164] = new State(new int[]{51,62},new int[]{-1,165});
    states[165] = new State(-25);
    states[166] = new State(-24);
    states[167] = new State(new int[]{34,164,35,-26,37,-26,23,-26,22,-26});
    states[168] = new State(-15);
    states[169] = new State(-21);
    states[170] = new State(-16);
    states[171] = new State(new int[]{20,135},new int[]{-29,172});
    states[172] = new State(-91);
    states[173] = new State(new int[]{51,62},new int[]{-3,174,-1,190});
    states[174] = new State(new int[]{28,175});
    states[175] = new State(new int[]{51,62,29,-108},new int[]{-34,176,-33,182,-32,189,-31,185,-1,188});
    states[176] = new State(new int[]{29,177});
    states[177] = new State(new int[]{36,178,38,179});
    states[178] = new State(-92);
    states[179] = new State(new int[]{51,62},new int[]{-39,180,-40,101,-1,110,-41,111});
    states[180] = new State(new int[]{36,181});
    states[181] = new State(-93);
    states[182] = new State(new int[]{35,183,29,-107});
    states[183] = new State(new int[]{51,62},new int[]{-32,184,-31,185,-1,188});
    states[184] = new State(-106);
    states[185] = new State(new int[]{36,186});
    states[186] = new State(new int[]{51,62},new int[]{-39,187,-40,101,-1,110,-41,111});
    states[187] = new State(-104);
    states[188] = new State(-103);
    states[189] = new State(-105);
    states[190] = new State(-75);
    states[191] = new State(-17);
    states[192] = new State(new int[]{51,62},new int[]{-37,193,-36,199,-1,196});
    states[193] = new State(new int[]{35,194,37,-18,23,-18,22,-18});
    states[194] = new State(new int[]{51,62},new int[]{-36,195,-1,196});
    states[195] = new State(-31);
    states[196] = new State(new int[]{16,197,35,-29,37,-29,23,-29,22,-29});
    states[197] = new State(new int[]{51,62},new int[]{-1,198});
    states[198] = new State(-28);
    states[199] = new State(-30);
    states[200] = new State(new int[]{51,62},new int[]{-1,201});
    states[201] = new State(new int[]{13,202});
    states[202] = new State(new int[]{47,204,51,62},new int[]{-37,203,-36,199,-1,196});
    states[203] = new State(new int[]{35,194,37,-19,23,-19,22,-19});
    states[204] = new State(-20);
    states[205] = new State(-115);
    states[206] = new State(-116);
    states[207] = new State(-3);
    states[208] = new State(new int[]{22,-117,51,-116,24,-116,25,-116,26,-116,27,-116,39,-116,32,-116,6,-116,5,-116,3,-116,10,-116,11,-116,12,-116,15,-116,17,-116,9,-116,13,-116,14,-116});

    rules[1] = new Rule(-48, new int[]{-30,2});
    rules[2] = new Rule(-30, new int[]{-28,-45,22});
    rules[3] = new Rule(-28, new int[]{-21});
    rules[4] = new Rule(-28, new int[]{-28,-46,-21});
    rules[5] = new Rule(-21, new int[]{-19});
    rules[6] = new Rule(-21, new int[]{-18});
    rules[7] = new Rule(-21, new int[]{-20});
    rules[8] = new Rule(-21, new int[]{-22});
    rules[9] = new Rule(-21, new int[]{-23});
    rules[10] = new Rule(-21, new int[]{-24});
    rules[11] = new Rule(-21, new int[]{-13});
    rules[12] = new Rule(-21, new int[]{-14});
    rules[13] = new Rule(-21, new int[]{-15});
    rules[14] = new Rule(-21, new int[]{-16});
    rules[15] = new Rule(-21, new int[]{-17});
    rules[16] = new Rule(-21, new int[]{-12});
    rules[17] = new Rule(-21, new int[]{-42});
    rules[18] = new Rule(-42, new int[]{13,-37});
    rules[19] = new Rule(-42, new int[]{14,-1,13,-37});
    rules[20] = new Rule(-42, new int[]{14,-1,13,47});
    rules[21] = new Rule(-17, new int[]{17});
    rules[22] = new Rule(-16, new int[]{15,-35});
    rules[23] = new Rule(-1, new int[]{51});
    rules[24] = new Rule(-2, new int[]{-1});
    rules[25] = new Rule(-2, new int[]{-2,34,-1});
    rules[26] = new Rule(-35, new int[]{-2});
    rules[27] = new Rule(-35, new int[]{-35,35,-2});
    rules[28] = new Rule(-36, new int[]{-1,16,-1});
    rules[29] = new Rule(-36, new int[]{-1});
    rules[30] = new Rule(-37, new int[]{-36});
    rules[31] = new Rule(-37, new int[]{-37,35,-36});
    rules[32] = new Rule(-18, new int[]{-7,36,-39});
    rules[33] = new Rule(-18, new int[]{-7,36,-39,40,-4});
    rules[34] = new Rule(-19, new int[]{-7,40,-4});
    rules[35] = new Rule(-19, new int[]{-7,-47,-4});
    rules[36] = new Rule(-47, new int[]{41});
    rules[37] = new Rule(-47, new int[]{42});
    rules[38] = new Rule(-47, new int[]{43});
    rules[39] = new Rule(-47, new int[]{44});
    rules[40] = new Rule(-4, new int[]{-4,6,-4,7,-4});
    rules[41] = new Rule(-4, new int[]{-4,45,-4});
    rules[42] = new Rule(-4, new int[]{-4,47,-4});
    rules[43] = new Rule(-4, new int[]{-4,48,-4});
    rules[44] = new Rule(-4, new int[]{-4,46,-4});
    rules[45] = new Rule(-4, new int[]{-4,52,-4});
    rules[46] = new Rule(-4, new int[]{-4,53,-4});
    rules[47] = new Rule(-4, new int[]{-4,54,-4});
    rules[48] = new Rule(-4, new int[]{-4,55,-4});
    rules[49] = new Rule(-4, new int[]{-4,56,-4});
    rules[50] = new Rule(-4, new int[]{-4,57,-4});
    rules[51] = new Rule(-4, new int[]{-4,58,-4});
    rules[52] = new Rule(-4, new int[]{-4,59,-4});
    rules[53] = new Rule(-4, new int[]{-4,49,-4});
    rules[54] = new Rule(-4, new int[]{-4,50,-4});
    rules[55] = new Rule(-4, new int[]{-4,61,-4});
    rules[56] = new Rule(-4, new int[]{46,-4});
    rules[57] = new Rule(-4, new int[]{60,-4});
    rules[58] = new Rule(-4, new int[]{-7});
    rules[59] = new Rule(-4, new int[]{-6});
    rules[60] = new Rule(-4, new int[]{28,-4,29});
    rules[61] = new Rule(-6, new int[]{24});
    rules[62] = new Rule(-6, new int[]{25});
    rules[63] = new Rule(-6, new int[]{26});
    rules[64] = new Rule(-6, new int[]{27});
    rules[65] = new Rule(-6, new int[]{39});
    rules[66] = new Rule(-27, new int[]{-4});
    rules[67] = new Rule(-27, new int[]{-27,35,-4});
    rules[68] = new Rule(-20, new int[]{6,-4,36,-29,-26});
    rules[69] = new Rule(-26, new int[]{8,-4,36,-29,-26});
    rules[70] = new Rule(-26, new int[]{-25});
    rules[71] = new Rule(-25, new int[]{7,36,-29});
    rules[72] = new Rule(-25, new int[]{});
    rules[73] = new Rule(-23, new int[]{5,-4,36,-29});
    rules[74] = new Rule(-24, new int[]{3,-1,4,-4,36,-29});
    rules[75] = new Rule(-3, new int[]{-1});
    rules[76] = new Rule(-13, new int[]{10,-4});
    rules[77] = new Rule(-13, new int[]{10});
    rules[78] = new Rule(-14, new int[]{11});
    rules[79] = new Rule(-15, new int[]{12});
    rules[80] = new Rule(-22, new int[]{-5});
    rules[81] = new Rule(-7, new int[]{-1});
    rules[82] = new Rule(-7, new int[]{-5});
    rules[83] = new Rule(-7, new int[]{-7,34,-1});
    rules[84] = new Rule(-7, new int[]{-6,34,-1});
    rules[85] = new Rule(-7, new int[]{32,-27,33});
    rules[86] = new Rule(-7, new int[]{-7,32,-4,33});
    rules[87] = new Rule(-7, new int[]{32,-4,3,-1,4,-4,-8,33});
    rules[88] = new Rule(-8, new int[]{});
    rules[89] = new Rule(-8, new int[]{6,-4});
    rules[90] = new Rule(-29, new int[]{20,-28,-46,21});
    rules[91] = new Rule(-12, new int[]{-38,-29});
    rules[92] = new Rule(-38, new int[]{9,-3,28,-34,29,36});
    rules[93] = new Rule(-38, new int[]{9,-3,28,-34,29,38,-39,36});
    rules[94] = new Rule(-5, new int[]{-7,28,-11,29});
    rules[95] = new Rule(-40, new int[]{-1});
    rules[96] = new Rule(-40, new int[]{-40,34,-1});
    rules[97] = new Rule(-39, new int[]{-40});
    rules[98] = new Rule(-39, new int[]{-41});
    rules[99] = new Rule(-41, new int[]{-40,-43});
    rules[100] = new Rule(-43, new int[]{32,-44,33});
    rules[101] = new Rule(-44, new int[]{-39});
    rules[102] = new Rule(-44, new int[]{-44,35,-39});
    rules[103] = new Rule(-31, new int[]{-1});
    rules[104] = new Rule(-32, new int[]{-31,36,-39});
    rules[105] = new Rule(-33, new int[]{-32});
    rules[106] = new Rule(-33, new int[]{-33,35,-32});
    rules[107] = new Rule(-34, new int[]{-33});
    rules[108] = new Rule(-34, new int[]{});
    rules[109] = new Rule(-9, new int[]{-4});
    rules[110] = new Rule(-9, new int[]{-1,40,-4});
    rules[111] = new Rule(-10, new int[]{-9});
    rules[112] = new Rule(-10, new int[]{-10,35,-9});
    rules[113] = new Rule(-11, new int[]{-10});
    rules[114] = new Rule(-11, new int[]{});
    rules[115] = new Rule(-46, new int[]{23});
    rules[116] = new Rule(-46, new int[]{37});
    rules[117] = new Rule(-45, new int[]{37});
    rules[118] = new Rule(-45, new int[]{});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // program -> stmt_list, optional_semicolon, END_OF_FILE
{
			// main program
			if (!is_unit_to_be_parsed) {
				var stl = ValueStack[ValueStack.Depth-3].stn as statement_list;
				stl.left_logical_bracket = new token_info("");
				stl.right_logical_bracket = new token_info("");
				var bl = new block(new declarations(), stl, CurrentLocationSpan);
				root = CurrentSemanticValue.stn = NewProgramModule(null, null, new uses_list(), bl, ValueStack[ValueStack.Depth-2].ob, CurrentLocationSpan);
				root.source_context = bl.source_context;
			}
			// unit
			else {
				var interface_part = new interface_node(new declarations(), new uses_list(), null, null);
				var initialization_part = new initfinal_part(null, ValueStack[ValueStack.Depth-3].stn as statement_list, null, null, null, CurrentLocationSpan);

				root = CurrentSemanticValue.stn = new unit_module(
					new unit_name(new ident(Path.GetFileNameWithoutExtension(parserTools.currentFileName)),
					UnitHeaderKeyword.Unit, CurrentLocationSpan), interface_part, null,
					initialization_part.initialization_sect,
					initialization_part.finalization_sect, null, CurrentLocationSpan);
			}

		}
        break;
      case 3: // stmt_list -> stmt
{
			CurrentSemanticValue.stn = new statement_list(ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 4: // stmt_list -> stmt_list, end_of_line, stmt
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as statement_list).Add(ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 5: // stmt -> assign_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 6: // stmt -> var_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 7: // stmt -> if_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 8: // stmt -> proc_func_call_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 9: // stmt -> while_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 10: // stmt -> for_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 11: // stmt -> return_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 12: // stmt -> break_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 13: // stmt -> continue_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 14: // stmt -> global_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 15: // stmt -> pass_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 16: // stmt -> proc_func_decl
{
			CurrentSemanticValue.stn = new declarations_as_statement(new declarations(ValueStack[ValueStack.Depth-1].stn as procedure_definition, CurrentLocationSpan), CurrentLocationSpan);
		}
        break;
      case 17: // stmt -> import_clause
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 18: // import_clause -> IMPORT, ident_as_ident_list
{
			CurrentSemanticValue.stn = new import_statement(ValueStack[ValueStack.Depth-1].stn as as_statement_list, CurrentLocationSpan);
		}
        break;
      case 19: // import_clause -> FROM, ident, IMPORT, ident_as_ident_list
{
			CurrentSemanticValue.stn = new from_import_statement(ValueStack[ValueStack.Depth-3].id as ident, false, ValueStack[ValueStack.Depth-1].stn as as_statement_list, CurrentLocationSpan);
		}
        break;
      case 20: // import_clause -> FROM, ident, IMPORT, STAR
{
			CurrentSemanticValue.stn = new from_import_statement(ValueStack[ValueStack.Depth-3].id as ident, true, null, CurrentLocationSpan);
		}
        break;
      case 21: // pass_stmt -> PASS
{
			CurrentSemanticValue.stn = new empty_statement();
		}
        break;
      case 22: // global_stmt -> GLOBAL, dotted_ident_list
{
			CurrentSemanticValue.stn = new global_statement(ValueStack[ValueStack.Depth-1].stn as ident_list, CurrentLocationSpan);
		}
        break;
      case 23: // ident -> ID
{
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id;
		}
        break;
      case 24: // dotted_ident -> ident
{ 
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id; 
		}
        break;
      case 25: // dotted_ident -> dotted_ident, DOT, ident
{ 
			CurrentSemanticValue.id = new ident(ValueStack[ValueStack.Depth-3].id.name + "." + ValueStack[ValueStack.Depth-1].id.name, CurrentLocationSpan); 
		}
        break;
      case 26: // dotted_ident_list -> dotted_ident
{
			CurrentSemanticValue.stn = new ident_list(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 27: // dotted_ident_list -> dotted_ident_list, COMMA, dotted_ident
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as ident_list).Add(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 28: // ident_as_ident -> ident, AS, ident
{ 
			CurrentSemanticValue.stn = new as_statement(ValueStack[ValueStack.Depth-3].id, ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan); 
		}
        break;
      case 29: // ident_as_ident -> ident
{ 
			CurrentSemanticValue.stn = new as_statement(ValueStack[ValueStack.Depth-1].id, ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan); 
		}
        break;
      case 30: // ident_as_ident_list -> ident_as_ident
{
			CurrentSemanticValue.stn = new as_statement_list(ValueStack[ValueStack.Depth-1].stn as as_statement, CurrentLocationSpan);
		}
        break;
      case 31: // ident_as_ident_list -> ident_as_ident_list, COMMA, ident_as_ident
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as as_statement_list).Add(ValueStack[ValueStack.Depth-1].stn as as_statement, CurrentLocationSpan);
		}
        break;
      case 32: // var_stmt -> variable, COLON, type_ref
{
			var vds = new var_def_statement(new ident_list(ValueStack[ValueStack.Depth-3].ex as ident, LocationStack[LocationStack.Depth-3]), ValueStack[ValueStack.Depth-1].td, null, definition_attribute.None, false, CurrentLocationSpan);
			CurrentSemanticValue.stn = new var_statement(vds, CurrentLocationSpan);
		}
        break;
      case 33: // var_stmt -> variable, COLON, type_ref, ASSIGN, expr
{
			var vds = new var_def_statement(new ident_list(ValueStack[ValueStack.Depth-5].ex as ident, LocationStack[LocationStack.Depth-5]), ValueStack[ValueStack.Depth-3].td, ValueStack[ValueStack.Depth-1].ex, definition_attribute.None, false, CurrentLocationSpan);
			CurrentSemanticValue.stn = new var_statement(vds, CurrentLocationSpan);
		}
        break;
      case 34: // assign_stmt -> variable, ASSIGN, expr
{
			if (!(ValueStack[ValueStack.Depth-3].ex is addressed_value))
        		parserTools.AddErrorFromResource("LEFT_SIDE_CANNOT_BE_ASSIGNED_TO", CurrentLocationSpan);
			CurrentSemanticValue.stn = new assign(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan);
		}
        break;
      case 35: // assign_stmt -> variable, assign_type, expr
{
			if (!(ValueStack[ValueStack.Depth-3].ex is addressed_value))
        		parserTools.AddErrorFromResource("LEFT_SIDE_CANNOT_BE_ASSIGNED_TO", CurrentLocationSpan);
			CurrentSemanticValue.stn = new assign(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan);
		}
        break;
      case 36: // assign_type -> PLUSEQUAL
{ 
			CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; 
		}
        break;
      case 37: // assign_type -> MINUSEQUAL
{ 
			CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; 
		}
        break;
      case 38: // assign_type -> STAREQUAL
{ 
			CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; 
		}
        break;
      case 39: // assign_type -> DIVEQUAL
{ 
			CurrentSemanticValue.op = ValueStack[ValueStack.Depth-1].op; 
		}
        break;
      case 40: // expr -> expr, IF, expr, ELSE, expr
{
			CurrentSemanticValue.ex = new question_colon_expression(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-5].ex, ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 41: // expr -> expr, PLUS, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 42: // expr -> expr, STAR, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 43: // expr -> expr, DIVIDE, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 44: // expr -> expr, MINUS, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 45: // expr -> expr, LESS, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 46: // expr -> expr, GREATER, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 47: // expr -> expr, LESSEQUAL, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 48: // expr -> expr, GREATEREQUAL, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 49: // expr -> expr, EQUAL, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 50: // expr -> expr, NOTEQUAL, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 51: // expr -> expr, AND, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 52: // expr -> expr, OR, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 53: // expr -> expr, SLASHSLASH, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 54: // expr -> expr, PERCENTAGE, expr
{ 
			CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 55: // expr -> expr, STARSTAR, expr
{
			addressed_value method_name = new ident("!pow", CurrentLocationSpan);
			expression_list el = new expression_list(new List<expression> { ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex }, CurrentLocationSpan);
			CurrentSemanticValue.ex = new method_call(method_name, el, CurrentLocationSpan);
		}
        break;
      case 56: // expr -> MINUS, expr
{ 
			CurrentSemanticValue.ex = new un_expr(ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 57: // expr -> NOT, expr
{ 
			CurrentSemanticValue.ex = new un_expr(ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); 
		}
        break;
      case 58: // expr -> variable
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 59: // expr -> const_value
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 60: // expr -> LPAR, expr, RPAR
{ 
			CurrentSemanticValue.ex = new bracket_expr(ValueStack[ValueStack.Depth-2].ex, CurrentLocationSpan); 
		}
        break;
      case 61: // const_value -> INTNUM
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 62: // const_value -> REALNUM
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 63: // const_value -> TRUE
{ 
			CurrentSemanticValue.ex = new ident("true", CurrentLocationSpan); 
		}
        break;
      case 64: // const_value -> FALSE
{ 
			CurrentSemanticValue.ex = new ident("false", CurrentLocationSpan); 
		}
        break;
      case 65: // const_value -> STRINGNUM
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].stn as literal; 
		}
        break;
      case 66: // expr_list -> expr
{
			CurrentSemanticValue.stn = new expression_list(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 67: // expr_list -> expr_list, COMMA, expr
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as expression_list).Add(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 68: // if_stmt -> IF, expr, COLON, block, optional_elif
{
			CurrentSemanticValue.stn = new if_node(ValueStack[ValueStack.Depth-4].ex, ValueStack[ValueStack.Depth-2].stn as statement, ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 69: // optional_elif -> ELIF, expr, COLON, block, optional_elif
{
			CurrentSemanticValue.stn = new if_node(ValueStack[ValueStack.Depth-4].ex, ValueStack[ValueStack.Depth-2].stn as statement, ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan);
		}
        break;
      case 70: // optional_elif -> optional_else
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 71: // optional_else -> ELSE, COLON, block
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 72: // optional_else -> /* empty */
{ 
			CurrentSemanticValue.stn = null; 
		}
        break;
      case 73: // while_stmt -> WHILE, expr, COLON, block
{
			CurrentSemanticValue.stn = new while_node(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].stn as statement, WhileCycleType.While, CurrentLocationSpan);
		}
        break;
      case 74: // for_stmt -> FOR, ident, IN, expr, COLON, block
{
			CurrentSemanticValue.stn = new foreach_stmt(ValueStack[ValueStack.Depth-5].id, new no_type_foreach(), ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].stn as statement, null, CurrentLocationSpan);
		}
        break;
      case 75: // func_name_ident -> ident
{
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id;
		}
        break;
      case 76: // return_stmt -> RETURN, expr
{
			statement res_assign = new assign(new ident("result"), ValueStack[ValueStack.Depth-1].ex, Operators.Assignment, CurrentLocationSpan);
			statement exit_call = new procedure_call(new ident("exit"), true, CurrentLocationSpan);
			CurrentSemanticValue.stn = new statement_list(res_assign, CurrentLocationSpan);
			(CurrentSemanticValue.stn as statement_list).Add(exit_call, CurrentLocationSpan);
		}
        break;
      case 77: // return_stmt -> RETURN
{
			CurrentSemanticValue.stn = new procedure_call(new ident("exit", CurrentLocationSpan), true, CurrentLocationSpan);
		}
        break;
      case 78: // break_stmt -> BREAK
{
			CurrentSemanticValue.stn = new procedure_call(new ident("break", CurrentLocationSpan), true, CurrentLocationSpan);
		}
        break;
      case 79: // continue_stmt -> CONTINUE
{
			CurrentSemanticValue.stn = new procedure_call(new ident("continue", CurrentLocationSpan), true, CurrentLocationSpan);
		}
        break;
      case 80: // proc_func_call_stmt -> proc_func_call
{
			CurrentSemanticValue.stn = new procedure_call(ValueStack[ValueStack.Depth-1].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex is ident, CurrentLocationSpan);
		}
        break;
      case 81: // variable -> ident
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].id; 
		}
        break;
      case 82: // variable -> proc_func_call
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 83: // variable -> variable, DOT, ident
{ 
			CurrentSemanticValue.ex = new dot_node(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].id as addressed_value, CurrentLocationSpan); 
		}
        break;
      case 84: // variable -> const_value, DOT, ident
{ 
			CurrentSemanticValue.ex = new dot_node(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].id as addressed_value, CurrentLocationSpan); 
		}
        break;
      case 85: // variable -> LBRACKET, expr_list, RBRACKET
{
			var acn = new array_const_new(ValueStack[ValueStack.Depth-2].stn as expression_list, '|', CurrentLocationSpan);
			var dn = new dot_node(acn as addressed_value, (new ident("ToList", CurrentLocationSpan)) as addressed_value, CurrentLocationSpan);
			CurrentSemanticValue.ex = new method_call(dn as addressed_value, null, CurrentLocationSpan);
		}
        break;
      case 86: // variable -> variable, LBRACKET, expr, RBRACKET
{
			var el = new expression_list(ValueStack[ValueStack.Depth-2].ex as expression, CurrentLocationSpan);
			CurrentSemanticValue.ex = new indexer(ValueStack[ValueStack.Depth-4].ex as addressed_value, el, CurrentLocationSpan);
		}
        break;
      case 87: // variable -> LBRACKET, expr, FOR, ident, IN, expr, optional_condition, RBRACKET
{
			CurrentSemanticValue.ex = new list_generator(ValueStack[ValueStack.Depth-7].ex, ValueStack[ValueStack.Depth-5].id, ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-2].ex, CurrentLocationSpan);
		}
        break;
      case 88: // optional_condition -> /* empty */
{ 
			CurrentSemanticValue.ex = null; 
		}
        break;
      case 89: // optional_condition -> IF, expr
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 90: // block -> INDENT, stmt_list, end_of_line, UNINDENT
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-3].stn as statement_list;
			(CurrentSemanticValue.stn as statement_list).left_logical_bracket = ValueStack[ValueStack.Depth-4].ti;
			(CurrentSemanticValue.stn as statement_list).right_logical_bracket = ValueStack[ValueStack.Depth-1].ti;
			CurrentSemanticValue.stn.source_context = LexLocation.MergeAll(LocationStack[LocationStack.Depth-3], LocationStack[LocationStack.Depth-2]);
		}
        break;
      case 91: // proc_func_decl -> proc_func_header, block
{
			CurrentSemanticValue.stn = new procedure_definition(ValueStack[ValueStack.Depth-2].td as procedure_header, new block(null, ValueStack[ValueStack.Depth-1].stn as statement_list, LocationStack[LocationStack.Depth-1]), CurrentLocationSpan);
		}
        break;
      case 92: // proc_func_header -> DEF, func_name_ident, LPAR, optional_form_param_list, RPAR, 
               //                     COLON
{
			CurrentSemanticValue.td = new procedure_header(ValueStack[ValueStack.Depth-3].stn as formal_parameters, new procedure_attributes_list(new List<procedure_attribute>()), new method_name(null,null, ValueStack[ValueStack.Depth-5].id, null, LocationStack[LocationStack.Depth-5]), null, CurrentLocationSpan);
		}
        break;
      case 93: // proc_func_header -> DEF, func_name_ident, LPAR, optional_form_param_list, RPAR, 
               //                     ARROW, type_ref, COLON
{
			CurrentSemanticValue.td = new function_header(ValueStack[ValueStack.Depth-5].stn as formal_parameters, new procedure_attributes_list(new List<procedure_attribute>()), new method_name(null,null, ValueStack[ValueStack.Depth-7].id, null, LocationStack[LocationStack.Depth-7]), null, ValueStack[ValueStack.Depth-2].td as type_definition, CurrentLocationSpan);
		}
        break;
      case 94: // proc_func_call -> variable, LPAR, optional_act_param_list, RPAR
{
			CurrentSemanticValue.ex = new method_call(ValueStack[ValueStack.Depth-4].ex as addressed_value, ValueStack[ValueStack.Depth-2].stn as expression_list, CurrentLocationSpan);
		}
        break;
      case 95: // simple_type_identifier -> ident
{
			CurrentSemanticValue.td = new named_type_reference(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 96: // simple_type_identifier -> simple_type_identifier, DOT, ident
{ 
			CurrentSemanticValue.td = (ValueStack[ValueStack.Depth-3].td as named_type_reference).Add(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 97: // type_ref -> simple_type_identifier
{
			CurrentSemanticValue.td = ValueStack[ValueStack.Depth-1].td as named_type_reference;
		}
        break;
      case 98: // type_ref -> template_type
{ 
			CurrentSemanticValue.td = ValueStack[ValueStack.Depth-1].td; 
		}
        break;
      case 99: // template_type -> simple_type_identifier, template_type_params
{ 
			CurrentSemanticValue.td = new template_type_reference(ValueStack[ValueStack.Depth-2].td as named_type_reference, ValueStack[ValueStack.Depth-1].stn as template_param_list, CurrentLocationSpan); 
		}
        break;
      case 100: // template_type_params -> LBRACKET, template_param_list, RBRACKET
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-2].stn;
			CurrentSemanticValue.stn.source_context = CurrentLocationSpan;
		}
        break;
      case 101: // template_param_list -> type_ref
{ 
			CurrentSemanticValue.stn = new template_param_list(ValueStack[ValueStack.Depth-1].td, CurrentLocationSpan);
		}
        break;
      case 102: // template_param_list -> template_param_list, COMMA, type_ref
{ 
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as template_param_list).Add(ValueStack[ValueStack.Depth-1].td, CurrentLocationSpan);
		}
        break;
      case 103: // param_name -> ident
{
			CurrentSemanticValue.stn = new ident_list(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 104: // form_param_sect -> param_name, COLON, type_ref
{
			CurrentSemanticValue.stn = new typed_parameters(ValueStack[ValueStack.Depth-3].stn as ident_list, ValueStack[ValueStack.Depth-1].td, parametr_kind.none, null, CurrentLocationSpan);
		}
        break;
      case 105: // form_param_list -> form_param_sect
{
			CurrentSemanticValue.stn = new formal_parameters(ValueStack[ValueStack.Depth-1].stn as typed_parameters, CurrentLocationSpan);
        }
        break;
      case 106: // form_param_list -> form_param_list, COMMA, form_param_sect
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as formal_parameters).Add(ValueStack[ValueStack.Depth-1].stn as typed_parameters, CurrentLocationSpan);
        }
        break;
      case 107: // optional_form_param_list -> form_param_list
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn;
		}
        break;
      case 108: // optional_form_param_list -> /* empty */
{
			CurrentSemanticValue.stn = null;
		}
        break;
      case 109: // act_param -> expr
{ 
			CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; 
		}
        break;
      case 110: // act_param -> ident, ASSIGN, expr
{ 
			CurrentSemanticValue.ex = new name_assign_expr(ValueStack[ValueStack.Depth-3].id, ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan); 
		}
        break;
      case 111: // act_param_list -> act_param
{
			CurrentSemanticValue.stn = new expression_list(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 112: // act_param_list -> act_param_list, COMMA, act_param
{
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as expression_list).Add(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan);
		}
        break;
      case 113: // optional_act_param_list -> act_param_list
{
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn;
		}
        break;
      case 114: // optional_act_param_list -> /* empty */
{
			CurrentSemanticValue.stn = null;
		}
        break;
      case 115: // end_of_line -> END_OF_LINE
{
			CurrentSemanticValue.ob = ValueStack[ValueStack.Depth-1].ti;
		}
        break;
      case 116: // end_of_line -> SEMICOLON
{
			CurrentSemanticValue.ob = ValueStack[ValueStack.Depth-1].ti;
		}
        break;
      case 117: // optional_semicolon -> SEMICOLON
{ 
			CurrentSemanticValue.ob = ValueStack[ValueStack.Depth-1].ti; 
		}
        break;
      case 118: // optional_semicolon -> /* empty */
{ 
			CurrentSemanticValue.ob = null; 
		}
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


        public program_module NewProgramModule(program_name progName, Object optHeadCompDirs, uses_list mainUsesClose, syntax_tree_node progBlock, Object optPoint, LexLocation loc)
        {
            var progModule = new program_module(progName, mainUsesClose, progBlock as block, null, loc);
            progModule.Language = "Spython";
            if (optPoint == null && progBlock != null)
            {
                var fp = progBlock.source_context.end_position;
                var err_stn = progBlock;
			    if ((progBlock is block) && (progBlock as block).program_code != null && (progBlock as block).program_code.subnodes != null && (progBlock as block).program_code.subnodes.Count > 0)
                    err_stn = (progBlock as block).program_code.subnodes[(progBlock as block).program_code.subnodes.Count - 1];
                //parserTools.errors.Add(new SPythonUnexpectedToken(parserTools.currentFileName, StringResources.Get("TKPOINT"), new SourceContext(fp.line_num, fp.column_num + 1, fp.line_num, fp.column_num + 1, 0, 0), err_stn));
            }
            return progModule;
        }
}
}
