// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  DESKTOP-56159VE
// DateTime: 10.03.2024 15:17:06
// UserName: ????
// Input file <ParserABC.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using PascalABCCompiler.SyntaxTree;
using PascalABCCompiler.ParserTools;
using PascalABCCompiler.Errors;
using System.Linq;
using System.Collections.Generic;
using VeryBasicParser;

namespace VeryBasicParserYacc
{
public enum Tokens {
    error=1,EOF=2,FOR=3,IN=4,WHILE=5,IF=6,
    ELSE=7,ELIF=8,DEF=9,RETURN=10,BREAK=11,CONTINUE=12,
    INTNUM=13,REALNUM=14,LPAR=15,RPAR=16,LBRACE=17,RBRACE=18,
    LBRACKET=19,RBRACKET=20,DOT=21,COMMA=22,COLON=23,SEMICOLON=24,
    INDENT=25,UNINDENT=26,ARROW=27,STRINGNUM=28,ASSIGN=29,PLUS=30,
    MINUS=31,MULTIPLY=32,DIVIDE=33,SLASHSLASH=34,PERCENTAGE=35,ID=36,
    INT=37,LESS=38,GREATER=39,LESSEQUAL=40,GREATEREQUAL=41,EQUAL=42,
    NOTEQUAL=43,AND=44,OR=45};

public partial struct ValueType
{
	public expression ex;
	public ident id;
    public Object ob;
    public op_type_node op;
    public syntax_tree_node stn;
    public token_info ti;
    public type_definition td;
}
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public partial class VeryBasicGPPGParser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from ParserABC.y
   	public syntax_tree_node root;
	public List<Error> errors;
    public string current_file_name;
    public int max_errors = 10;
	public VeryBasicParserTools parsertools;
    public List<compiler_directive> CompilerDirectives;
   	public VeryBasicGPPGParser(AbstractScanner<ValueType, LexLocation> scanner) : base(scanner) { }

	private SymbolTable symbolTable = new SymbolTable();
	private declarations decl_forward = new declarations();
	private declarations decl = new declarations();
  // End verbatim content from ParserABC.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[80];
  private static State[] states = new State[141];
  private static string[] nonTerms = new string[] {
      "identifier", "expr", "var_reference", "variable", "proc_func_call", "range_expr", 
      "constant_value", "expr_lst", "optional_expr_lst", "proc_func_decl", "return_stmt", 
      "break_stmt", "continue_stmt", "assign", "if_stmt", "stmt", "proccall", 
      "while_stmt", "for_stmt", "optional_else", "optional_elif", "decl_or_stmt", 
      "decl_or_stmt_list", "stmt_lst", "compound_stmt", "proc_func_body", "progr", 
      "decl", "param_name", "simple_fp_sect", "fp_sect", "fp_sect_list", "fp_list", 
      "proc_func_header", "fp_type", "simple_type_identifier", "$accept", "NestedSymbolTableBegin", 
      "NestedSymbolTableEnd", };

  static VeryBasicGPPGParser() {
    states[0] = new State(new int[]{36,47,6,71,13,52,14,53,28,54,5,90,3,95,10,102,11,105,12,107,25,-63,9,-63},new int[]{-27,1,-23,3,-22,140,-16,6,-14,7,-1,8,-25,61,-38,62,-15,70,-17,85,-3,86,-4,87,-5,48,-7,88,-18,89,-19,94,-11,101,-12,104,-13,106,-28,138,-10,139});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{24,4,2,-2});
    states[4] = new State(new int[]{36,47,6,71,13,52,14,53,28,54,5,90,3,95,10,102,11,105,12,107,25,-63,9,-63},new int[]{-22,5,-16,6,-14,7,-1,8,-25,61,-38,62,-15,70,-17,85,-3,86,-4,87,-5,48,-7,88,-18,89,-19,94,-11,101,-12,104,-13,106,-28,138,-10,139});
    states[5] = new State(-7);
    states[6] = new State(-3);
    states[7] = new State(-10);
    states[8] = new State(new int[]{29,9,15,-58,21,-58,24,-58,2,-58});
    states[9] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,10,-4,39,-1,46,-5,48,-7,49});
    states[10] = new State(new int[]{30,11,32,13,33,15,31,17,38,19,39,21,40,23,41,25,42,27,43,29,44,31,45,33,34,35,35,37,24,-20,2,-20});
    states[11] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,12,-4,39,-1,46,-5,48,-7,49});
    states[12] = new State(new int[]{30,-21,32,13,33,15,31,-21,38,-21,39,-21,40,-21,41,-21,42,-21,43,-21,44,-21,45,-21,34,35,35,37,24,-21,2,-21,22,-21,16,-21,23,-21});
    states[13] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,14,-4,39,-1,46,-5,48,-7,49});
    states[14] = new State(-22);
    states[15] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,16,-4,39,-1,46,-5,48,-7,49});
    states[16] = new State(-23);
    states[17] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,18,-4,39,-1,46,-5,48,-7,49});
    states[18] = new State(new int[]{30,-24,32,13,33,15,31,-24,38,-24,39,-24,40,-24,41,-24,42,-24,43,-24,44,-24,45,-24,34,35,35,37,24,-24,2,-24,22,-24,16,-24,23,-24});
    states[19] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,20,-4,39,-1,46,-5,48,-7,49});
    states[20] = new State(new int[]{30,11,32,13,33,15,31,17,38,-25,39,-25,40,-25,41,-25,42,-25,43,-25,44,-25,45,-25,34,35,35,37,24,-25,2,-25,22,-25,16,-25,23,-25});
    states[21] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,22,-4,39,-1,46,-5,48,-7,49});
    states[22] = new State(new int[]{30,11,32,13,33,15,31,17,38,-26,39,-26,40,-26,41,-26,42,-26,43,-26,44,-26,45,-26,34,35,35,37,24,-26,2,-26,22,-26,16,-26,23,-26});
    states[23] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,24,-4,39,-1,46,-5,48,-7,49});
    states[24] = new State(new int[]{30,11,32,13,33,15,31,17,38,-27,39,-27,40,-27,41,-27,42,-27,43,-27,44,-27,45,-27,34,35,35,37,24,-27,2,-27,22,-27,16,-27,23,-27});
    states[25] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,26,-4,39,-1,46,-5,48,-7,49});
    states[26] = new State(new int[]{30,11,32,13,33,15,31,17,38,-28,39,-28,40,-28,41,-28,42,-28,43,-28,44,-28,45,-28,34,35,35,37,24,-28,2,-28,22,-28,16,-28,23,-28});
    states[27] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,28,-4,39,-1,46,-5,48,-7,49});
    states[28] = new State(new int[]{30,11,32,13,33,15,31,17,38,-29,39,-29,40,-29,41,-29,42,-29,43,-29,44,-29,45,-29,34,35,35,37,24,-29,2,-29,22,-29,16,-29,23,-29});
    states[29] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,30,-4,39,-1,46,-5,48,-7,49});
    states[30] = new State(new int[]{30,11,32,13,33,15,31,17,38,-30,39,-30,40,-30,41,-30,42,-30,43,-30,44,-30,45,-30,34,35,35,37,24,-30,2,-30,22,-30,16,-30,23,-30});
    states[31] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,32,-4,39,-1,46,-5,48,-7,49});
    states[32] = new State(new int[]{30,11,32,13,33,15,31,17,38,19,39,21,40,23,41,25,42,27,43,29,44,-31,45,-31,34,35,35,37,24,-31,2,-31,22,-31,16,-31,23,-31});
    states[33] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,34,-4,39,-1,46,-5,48,-7,49});
    states[34] = new State(new int[]{30,11,32,13,33,15,31,17,38,19,39,21,40,23,41,25,42,27,43,29,44,31,45,-32,34,35,35,37,24,-32,2,-32,22,-32,16,-32,23,-32});
    states[35] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,36,-4,39,-1,46,-5,48,-7,49});
    states[36] = new State(-33);
    states[37] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,38,-4,39,-1,46,-5,48,-7,49});
    states[38] = new State(-34);
    states[39] = new State(new int[]{15,40,21,59,30,-35,32,-35,33,-35,31,-35,38,-35,39,-35,40,-35,41,-35,42,-35,43,-35,44,-35,45,-35,34,-35,35,-35,24,-35,2,-35,22,-35,16,-35,23,-35});
    states[40] = new State(new int[]{36,47,13,52,14,53,28,54,15,55,16,-42},new int[]{-9,41,-8,43,-2,58,-4,39,-1,46,-5,48,-7,49});
    states[41] = new State(new int[]{16,42});
    states[42] = new State(-69);
    states[43] = new State(new int[]{22,44,16,-41});
    states[44] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,45,-4,39,-1,46,-5,48,-7,49});
    states[45] = new State(new int[]{30,11,32,13,33,15,31,17,38,19,39,21,40,23,41,25,42,27,43,29,44,31,45,33,34,35,35,37,22,-44,16,-44});
    states[46] = new State(-58);
    states[47] = new State(-19);
    states[48] = new State(-59);
    states[49] = new State(new int[]{21,50,30,-36,32,-36,33,-36,31,-36,38,-36,39,-36,40,-36,41,-36,42,-36,43,-36,44,-36,45,-36,34,-36,35,-36,24,-36,2,-36,22,-36,16,-36,23,-36});
    states[50] = new State(new int[]{36,47},new int[]{-1,51});
    states[51] = new State(-61);
    states[52] = new State(-38);
    states[53] = new State(-39);
    states[54] = new State(-40);
    states[55] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,56,-4,39,-1,46,-5,48,-7,49});
    states[56] = new State(new int[]{16,57,30,11,32,13,33,15,31,17,38,19,39,21,40,23,41,25,42,27,43,29,44,31,45,33,34,35,35,37});
    states[57] = new State(-37);
    states[58] = new State(new int[]{30,11,32,13,33,15,31,17,38,19,39,21,40,23,41,25,42,27,43,29,44,31,45,33,34,35,35,37,22,-43,16,-43});
    states[59] = new State(new int[]{36,47},new int[]{-1,60});
    states[60] = new State(-60);
    states[61] = new State(-11);
    states[62] = new State(new int[]{25,63,9,116},new int[]{-34,109});
    states[63] = new State(new int[]{36,47,6,71,13,52,14,53,28,54,5,90,3,95,10,102,11,105,12,107,25,-63},new int[]{-24,64,-16,108,-14,7,-1,8,-25,61,-38,69,-15,70,-17,85,-3,86,-4,87,-5,48,-7,88,-18,89,-19,94,-11,101,-12,104,-13,106});
    states[64] = new State(new int[]{24,65});
    states[65] = new State(new int[]{26,66,36,47,6,71,13,52,14,53,28,54,5,90,3,95,10,102,11,105,12,107,25,-63},new int[]{-16,68,-14,7,-1,8,-25,61,-38,69,-15,70,-17,85,-3,86,-4,87,-5,48,-7,88,-18,89,-19,94,-11,101,-12,104,-13,106});
    states[66] = new State(-64,new int[]{-39,67});
    states[67] = new State(-62);
    states[68] = new State(-9);
    states[69] = new State(new int[]{25,63});
    states[70] = new State(-12);
    states[71] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,72,-4,39,-1,46,-5,48,-7,49});
    states[72] = new State(new int[]{23,73,30,11,32,13,33,15,31,17,38,19,39,21,40,23,41,25,42,27,43,29,44,31,45,33,34,35,35,37});
    states[73] = new State(-63,new int[]{-25,74,-38,69});
    states[74] = new State(new int[]{8,76,7,82,24,-49,2,-49},new int[]{-21,75,-20,81});
    states[75] = new State(-45);
    states[76] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,77,-4,39,-1,46,-5,48,-7,49});
    states[77] = new State(new int[]{23,78,30,11,32,13,33,15,31,17,38,19,39,21,40,23,41,25,42,27,43,29,44,31,45,33,34,35,35,37});
    states[78] = new State(-63,new int[]{-25,79,-38,69});
    states[79] = new State(new int[]{8,76,7,82,24,-49,2,-49},new int[]{-21,80,-20,81});
    states[80] = new State(-46);
    states[81] = new State(-47);
    states[82] = new State(new int[]{23,83});
    states[83] = new State(-63,new int[]{-25,84,-38,69});
    states[84] = new State(-48);
    states[85] = new State(-13);
    states[86] = new State(-56);
    states[87] = new State(new int[]{15,40,21,59,24,-57,2,-57});
    states[88] = new State(new int[]{21,50});
    states[89] = new State(-14);
    states[90] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,91,-4,39,-1,46,-5,48,-7,49});
    states[91] = new State(new int[]{23,92,30,11,32,13,33,15,31,17,38,19,39,21,40,23,41,25,42,27,43,29,44,31,45,33,34,35,35,37});
    states[92] = new State(-63,new int[]{-25,93,-38,69});
    states[93] = new State(-50);
    states[94] = new State(-15);
    states[95] = new State(new int[]{36,47},new int[]{-1,96});
    states[96] = new State(new int[]{4,97});
    states[97] = new State(new int[]{36,47,13,52,14,53,28,54,15,55},new int[]{-2,98,-4,39,-1,46,-5,48,-7,49});
    states[98] = new State(new int[]{23,99,30,11,32,13,33,15,31,17,38,19,39,21,40,23,41,25,42,27,43,29,44,31,45,33,34,35,35,37});
    states[99] = new State(-63,new int[]{-25,100,-38,69});
    states[100] = new State(-51);
    states[101] = new State(-16);
    states[102] = new State(new int[]{36,47,13,52,14,53,28,54,15,55,24,-53,2,-53},new int[]{-2,103,-4,39,-1,46,-5,48,-7,49});
    states[103] = new State(new int[]{30,11,32,13,33,15,31,17,38,19,39,21,40,23,41,25,42,27,43,29,44,31,45,33,34,35,35,37,24,-52,2,-52});
    states[104] = new State(-17);
    states[105] = new State(-54);
    states[106] = new State(-18);
    states[107] = new State(-55);
    states[108] = new State(-8);
    states[109] = new State(new int[]{25,112},new int[]{-26,110});
    states[110] = new State(-64,new int[]{-39,111});
    states[111] = new State(-66);
    states[112] = new State(new int[]{36,47,6,71,13,52,14,53,28,54,5,90,3,95,10,102,11,105,12,107,25,-63},new int[]{-24,113,-16,108,-14,7,-1,8,-25,61,-38,69,-15,70,-17,85,-3,86,-4,87,-5,48,-7,88,-18,89,-19,94,-11,101,-12,104,-13,106});
    states[113] = new State(new int[]{24,114});
    states[114] = new State(new int[]{26,115,36,47,6,71,13,52,14,53,28,54,5,90,3,95,10,102,11,105,12,107,25,-63},new int[]{-16,68,-14,7,-1,8,-25,61,-38,69,-15,70,-17,85,-3,86,-4,87,-5,48,-7,88,-18,89,-19,94,-11,101,-12,104,-13,106});
    states[115] = new State(-65);
    states[116] = new State(new int[]{36,47},new int[]{-1,117});
    states[117] = new State(new int[]{15,126},new int[]{-33,118});
    states[118] = new State(new int[]{23,119,27,120});
    states[119] = new State(-67);
    states[120] = new State(new int[]{36,47},new int[]{-35,121,-6,123,-36,124,-1,125});
    states[121] = new State(new int[]{23,122});
    states[122] = new State(-68);
    states[123] = new State(-72);
    states[124] = new State(-71);
    states[125] = new State(-70);
    states[126] = new State(new int[]{16,127,36,47},new int[]{-32,128,-31,137,-30,132,-29,133,-1,136});
    states[127] = new State(-78);
    states[128] = new State(new int[]{16,129,22,130});
    states[129] = new State(-79);
    states[130] = new State(new int[]{36,47},new int[]{-31,131,-30,132,-29,133,-1,136});
    states[131] = new State(-77);
    states[132] = new State(-75);
    states[133] = new State(new int[]{23,134});
    states[134] = new State(new int[]{36,47},new int[]{-35,135,-6,123,-36,124,-1,125});
    states[135] = new State(-74);
    states[136] = new State(-73);
    states[137] = new State(-76);
    states[138] = new State(-4);
    states[139] = new State(-5);
    states[140] = new State(-6);

    rules[1] = new Rule(-37, new int[]{-27,2});
    rules[2] = new Rule(-27, new int[]{-23});
    rules[3] = new Rule(-22, new int[]{-16});
    rules[4] = new Rule(-22, new int[]{-28});
    rules[5] = new Rule(-28, new int[]{-10});
    rules[6] = new Rule(-23, new int[]{-22});
    rules[7] = new Rule(-23, new int[]{-23,24,-22});
    rules[8] = new Rule(-24, new int[]{-16});
    rules[9] = new Rule(-24, new int[]{-24,24,-16});
    rules[10] = new Rule(-16, new int[]{-14});
    rules[11] = new Rule(-16, new int[]{-25});
    rules[12] = new Rule(-16, new int[]{-15});
    rules[13] = new Rule(-16, new int[]{-17});
    rules[14] = new Rule(-16, new int[]{-18});
    rules[15] = new Rule(-16, new int[]{-19});
    rules[16] = new Rule(-16, new int[]{-11});
    rules[17] = new Rule(-16, new int[]{-12});
    rules[18] = new Rule(-16, new int[]{-13});
    rules[19] = new Rule(-1, new int[]{36});
    rules[20] = new Rule(-14, new int[]{-1,29,-2});
    rules[21] = new Rule(-2, new int[]{-2,30,-2});
    rules[22] = new Rule(-2, new int[]{-2,32,-2});
    rules[23] = new Rule(-2, new int[]{-2,33,-2});
    rules[24] = new Rule(-2, new int[]{-2,31,-2});
    rules[25] = new Rule(-2, new int[]{-2,38,-2});
    rules[26] = new Rule(-2, new int[]{-2,39,-2});
    rules[27] = new Rule(-2, new int[]{-2,40,-2});
    rules[28] = new Rule(-2, new int[]{-2,41,-2});
    rules[29] = new Rule(-2, new int[]{-2,42,-2});
    rules[30] = new Rule(-2, new int[]{-2,43,-2});
    rules[31] = new Rule(-2, new int[]{-2,44,-2});
    rules[32] = new Rule(-2, new int[]{-2,45,-2});
    rules[33] = new Rule(-2, new int[]{-2,34,-2});
    rules[34] = new Rule(-2, new int[]{-2,35,-2});
    rules[35] = new Rule(-2, new int[]{-4});
    rules[36] = new Rule(-2, new int[]{-7});
    rules[37] = new Rule(-2, new int[]{15,-2,16});
    rules[38] = new Rule(-7, new int[]{13});
    rules[39] = new Rule(-7, new int[]{14});
    rules[40] = new Rule(-7, new int[]{28});
    rules[41] = new Rule(-9, new int[]{-8});
    rules[42] = new Rule(-9, new int[]{});
    rules[43] = new Rule(-8, new int[]{-2});
    rules[44] = new Rule(-8, new int[]{-8,22,-2});
    rules[45] = new Rule(-15, new int[]{6,-2,23,-25,-21});
    rules[46] = new Rule(-21, new int[]{8,-2,23,-25,-21});
    rules[47] = new Rule(-21, new int[]{-20});
    rules[48] = new Rule(-20, new int[]{7,23,-25});
    rules[49] = new Rule(-20, new int[]{});
    rules[50] = new Rule(-18, new int[]{5,-2,23,-25});
    rules[51] = new Rule(-19, new int[]{3,-1,4,-2,23,-25});
    rules[52] = new Rule(-11, new int[]{10,-2});
    rules[53] = new Rule(-11, new int[]{10});
    rules[54] = new Rule(-12, new int[]{11});
    rules[55] = new Rule(-13, new int[]{12});
    rules[56] = new Rule(-17, new int[]{-3});
    rules[57] = new Rule(-3, new int[]{-4});
    rules[58] = new Rule(-4, new int[]{-1});
    rules[59] = new Rule(-4, new int[]{-5});
    rules[60] = new Rule(-4, new int[]{-4,21,-1});
    rules[61] = new Rule(-4, new int[]{-7,21,-1});
    rules[62] = new Rule(-25, new int[]{-38,25,-24,24,26,-39});
    rules[63] = new Rule(-38, new int[]{});
    rules[64] = new Rule(-39, new int[]{});
    rules[65] = new Rule(-26, new int[]{25,-24,24,26});
    rules[66] = new Rule(-10, new int[]{-38,-34,-26,-39});
    rules[67] = new Rule(-34, new int[]{9,-1,-33,23});
    rules[68] = new Rule(-34, new int[]{9,-1,-33,27,-35,23});
    rules[69] = new Rule(-5, new int[]{-4,15,-9,16});
    rules[70] = new Rule(-36, new int[]{-1});
    rules[71] = new Rule(-6, new int[]{-36});
    rules[72] = new Rule(-35, new int[]{-6});
    rules[73] = new Rule(-29, new int[]{-1});
    rules[74] = new Rule(-30, new int[]{-29,23,-35});
    rules[75] = new Rule(-31, new int[]{-30});
    rules[76] = new Rule(-32, new int[]{-31});
    rules[77] = new Rule(-32, new int[]{-32,22,-31});
    rules[78] = new Rule(-33, new int[]{15,16});
    rules[79] = new Rule(-33, new int[]{15,-32,16});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // progr -> decl_or_stmt_list
{
			var stl = ValueStack[ValueStack.Depth-1].stn as statement_list;
			decl.AddFirst(decl_forward.defs);
			// добавляем нод�? ини�?иализа�?ии глобал�?н�?�? пе�?еменн�?�?
			// foreach (string elem in symbolTable) {
			// 	var vds = new var_def_statement(new ident_list(new ident(elem)), null, new int32_const(0), definition_attribute.None, false, @$);
			// 	stl.AddFirst((new var_statement(vds, @$)) as statement);
			// }
			root = CurrentSemanticValue.stn = NewProgramModule(null, null, null, new block(decl, stl, CurrentLocationSpan), new token_info(""), CurrentLocationSpan);
			CurrentSemanticValue.stn.source_context = CurrentLocationSpan;
		}
        break;
      case 3: // decl_or_stmt -> stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 4: // decl_or_stmt -> decl
{ CurrentSemanticValue.stn = null; }
        break;
      case 5: // decl -> proc_func_decl
{
			CurrentSemanticValue.stn = null; 
			decl.Add(ValueStack[ValueStack.Depth-1].stn as procedure_definition, CurrentLocationSpan);
		}
        break;
      case 6: // decl_or_stmt_list -> decl_or_stmt
{
			if (ValueStack[ValueStack.Depth-1].stn is statement st)
				CurrentSemanticValue.stn = new statement_list(ValueStack[ValueStack.Depth-1].stn as statement, LocationStack[LocationStack.Depth-1]);
			else
				CurrentSemanticValue.stn =  new statement_list(); 
		}
        break;
      case 7: // decl_or_stmt_list -> decl_or_stmt_list, SEMICOLON, decl_or_stmt
{
			if (ValueStack[ValueStack.Depth-1].stn is statement st) 
				CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as statement_list).Add(st, CurrentLocationSpan);
			else 
				CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as statement_list);
		}
        break;
      case 8: // stmt_lst -> stmt
{ 
			CurrentSemanticValue.stn = new statement_list(ValueStack[ValueStack.Depth-1].stn as statement, LocationStack[LocationStack.Depth-1]); 
		}
        break;
      case 9: // stmt_lst -> stmt_lst, SEMICOLON, stmt
{ 
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as statement_list).Add(ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan); 
		}
        break;
      case 10: // stmt -> assign
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 11: // stmt -> compound_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 12: // stmt -> if_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 13: // stmt -> proccall
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 14: // stmt -> while_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 15: // stmt -> for_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 16: // stmt -> return_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 17: // stmt -> break_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 18: // stmt -> continue_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 19: // identifier -> ID
{
			if (ValueStack[ValueStack.Depth-1].id.name == "result")
				ValueStack[ValueStack.Depth-1].id.name = "%result";
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id; 
		}
        break;
      case 20: // assign -> identifier, ASSIGN, expr
{
			if (!symbolTable.Contains(ValueStack[ValueStack.Depth-3].id.name)) {
				symbolTable.Add(ValueStack[ValueStack.Depth-3].id.name);
				var vds = new var_def_statement(new ident_list(ValueStack[ValueStack.Depth-3].id, LocationStack[LocationStack.Depth-3]), null, ValueStack[ValueStack.Depth-1].ex, definition_attribute.None, false, CurrentLocationSpan);
				CurrentSemanticValue.stn = new var_statement(vds, CurrentLocationSpan);
			}
			else {
				CurrentSemanticValue.stn = new assign(ValueStack[ValueStack.Depth-3].id as addressed_value, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan);
			}
			// symbolTable.Add($1.name);
			// $$ = new assign($1 as addressed_value, $3, $2.type, @$);
		}
        break;
      case 21: // expr -> expr, PLUS, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 22: // expr -> expr, MULTIPLY, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 23: // expr -> expr, DIVIDE, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 24: // expr -> expr, MINUS, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 25: // expr -> expr, LESS, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 26: // expr -> expr, GREATER, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 27: // expr -> expr, LESSEQUAL, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 28: // expr -> expr, GREATEREQUAL, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 29: // expr -> expr, EQUAL, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 30: // expr -> expr, NOTEQUAL, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 31: // expr -> expr, AND, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 32: // expr -> expr, OR, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 33: // expr -> expr, SLASHSLASH, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 34: // expr -> expr, PERCENTAGE, expr
{ CurrentSemanticValue.ex = new bin_expr(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].ex, ValueStack[ValueStack.Depth-2].op.type, CurrentLocationSpan); }
        break;
      case 35: // expr -> variable
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 36: // expr -> constant_value
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 37: // expr -> LPAR, expr, RPAR
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-2].ex; }
        break;
      case 38: // constant_value -> INTNUM
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 39: // constant_value -> REALNUM
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 40: // constant_value -> STRINGNUM
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].stn as literal; }
        break;
      case 41: // optional_expr_lst -> expr_lst
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 42: // optional_expr_lst -> /* empty */
{ CurrentSemanticValue.stn = null; }
        break;
      case 43: // expr_lst -> expr
{ 
			CurrentSemanticValue.stn = new expression_list(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan); 
		}
        break;
      case 44: // expr_lst -> expr_lst, COMMA, expr
{ 
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as expression_list).Add(ValueStack[ValueStack.Depth-1].ex, CurrentLocationSpan); 
		}
        break;
      case 45: // if_stmt -> IF, expr, COLON, compound_stmt, optional_elif
{ 
			CurrentSemanticValue.stn = new if_node(ValueStack[ValueStack.Depth-4].ex, ValueStack[ValueStack.Depth-2].stn as statement, ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan); 
		}
        break;
      case 46: // optional_elif -> ELIF, expr, COLON, compound_stmt, optional_elif
{ 
			CurrentSemanticValue.stn = new if_node(ValueStack[ValueStack.Depth-4].ex, ValueStack[ValueStack.Depth-2].stn as statement, ValueStack[ValueStack.Depth-1].stn as statement, CurrentLocationSpan); 
		}
        break;
      case 47: // optional_elif -> optional_else
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 48: // optional_else -> ELSE, COLON, compound_stmt
{ CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; }
        break;
      case 49: // optional_else -> /* empty */
{ CurrentSemanticValue.stn = null; }
        break;
      case 50: // while_stmt -> WHILE, expr, COLON, compound_stmt
{ 
			CurrentSemanticValue.stn = new while_node(ValueStack[ValueStack.Depth-3].ex, ValueStack[ValueStack.Depth-1].stn as statement, WhileCycleType.While, CurrentLocationSpan); 
		}
        break;
      case 51: // for_stmt -> FOR, identifier, IN, expr, COLON, compound_stmt
{ 
			CurrentSemanticValue.stn = new foreach_stmt(ValueStack[ValueStack.Depth-5].id, new no_type_foreach(), ValueStack[ValueStack.Depth-3].ex, (statement)ValueStack[ValueStack.Depth-1].stn, null, CurrentLocationSpan); 
		}
        break;
      case 52: // return_stmt -> RETURN, expr
{
			statement res_assign = new assign(new ident("result"), ValueStack[ValueStack.Depth-1].ex, Operators.Assignment, CurrentLocationSpan);
			statement exit_call = new procedure_call(new ident("exit"), true, CurrentLocationSpan);
			CurrentSemanticValue.stn = new statement_list(res_assign, CurrentLocationSpan);
			(CurrentSemanticValue.stn  as statement_list).Add(exit_call, CurrentLocationSpan);
		}
        break;
      case 53: // return_stmt -> RETURN
{
			CurrentSemanticValue.stn = new procedure_call(new ident("exit"), true, CurrentLocationSpan);
		}
        break;
      case 54: // break_stmt -> BREAK
{
			CurrentSemanticValue.stn = new procedure_call(new ident("break"), true, CurrentLocationSpan);
		}
        break;
      case 55: // continue_stmt -> CONTINUE
{
			CurrentSemanticValue.stn = new procedure_call(new ident("continue"), true, CurrentLocationSpan);
		}
        break;
      case 56: // proccall -> var_reference
{
			CurrentSemanticValue.stn = new procedure_call(ValueStack[ValueStack.Depth-1].ex as addressed_value, ValueStack[ValueStack.Depth-1].ex is ident, CurrentLocationSpan);
		}
        break;
      case 57: // var_reference -> variable
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 58: // variable -> identifier
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].id; }
        break;
      case 59: // variable -> proc_func_call
{ CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].ex; }
        break;
      case 60: // variable -> variable, DOT, identifier
{ CurrentSemanticValue.ex = new dot_node(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].id as addressed_value, CurrentLocationSpan); }
        break;
      case 61: // variable -> constant_value, DOT, identifier
{ CurrentSemanticValue.ex = new dot_node(ValueStack[ValueStack.Depth-3].ex as addressed_value, ValueStack[ValueStack.Depth-1].id as addressed_value, CurrentLocationSpan); }
        break;
      case 62: // compound_stmt -> NestedSymbolTableBegin, INDENT, stmt_lst, SEMICOLON, UNINDENT, 
               //                  NestedSymbolTableEnd
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-4].stn as statement_list; 
			(CurrentSemanticValue.stn as statement_list).left_logical_bracket = ValueStack[ValueStack.Depth-5].ti;
			(CurrentSemanticValue.stn as statement_list).right_logical_bracket = ValueStack[ValueStack.Depth-2].ti;
			CurrentSemanticValue.stn.source_context = CurrentLocationSpan;
		}
        break;
      case 63: // NestedSymbolTableBegin -> /* empty */
{ 
			symbolTable = new SymbolTable(symbolTable); 
		}
        break;
      case 64: // NestedSymbolTableEnd -> /* empty */
{ 
			symbolTable = symbolTable.OuterScope;
		}
        break;
      case 65: // proc_func_body -> INDENT, stmt_lst, SEMICOLON, UNINDENT
{	
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-3].stn as statement_list; 
			(CurrentSemanticValue.stn as statement_list).left_logical_bracket = ValueStack[ValueStack.Depth-4].ti;
			(CurrentSemanticValue.stn as statement_list).right_logical_bracket = ValueStack[ValueStack.Depth-1].ti;
			CurrentSemanticValue.stn.source_context = CurrentLocationSpan;
		}
        break;
      case 66: // proc_func_decl -> NestedSymbolTableBegin, proc_func_header, proc_func_body, 
               //                   NestedSymbolTableEnd
{
			//var pd1 = new procedure_definition($1 as procedure_header, new block(null, $2 as statement_list, @2), @$);
			//pd1.AssignAttrList(null);
			//$$ = pd1;
			CurrentSemanticValue.stn = new procedure_definition(ValueStack[ValueStack.Depth-3].td as procedure_header, new block(null, ValueStack[ValueStack.Depth-2].stn as statement_list, LocationStack[LocationStack.Depth-2]), CurrentLocationSpan);

			var pd = new procedure_definition(ValueStack[ValueStack.Depth-3].td as procedure_header, null, LocationStack[LocationStack.Depth-3]);
            pd.proc_header.proc_attributes.Add(new procedure_attribute(proc_attribute.attr_forward));
			decl_forward.Add(pd, LocationStack[LocationStack.Depth-3]);
		}
        break;
      case 67: // proc_func_header -> DEF, identifier, fp_list, COLON
{
			// надо добави�?�? все имена (из fp_list) пе�?еменн�?�? в symbolTable
			// symbolTable = new SymbolTable(symbolTable); 
			CurrentSemanticValue.td = new procedure_header(ValueStack[ValueStack.Depth-2].stn as formal_parameters, new procedure_attributes_list(new List<procedure_attribute>(), CurrentLocationSpan), new method_name(null,null, ValueStack[ValueStack.Depth-3].id, null, CurrentLocationSpan), null, CurrentLocationSpan); 
		}
        break;
      case 68: // proc_func_header -> DEF, identifier, fp_list, ARROW, fp_type, COLON
{
			// надо добави�?�? все имена (из fp_list) пе�?еменн�?�? в symbolTable
			// symbolTable = new SymbolTable(symbolTable); 
			CurrentSemanticValue.td = new function_header(ValueStack[ValueStack.Depth-4].stn as formal_parameters, new procedure_attributes_list(new List<procedure_attribute>(), CurrentLocationSpan), new method_name(null,null, ValueStack[ValueStack.Depth-5].id, null, CurrentLocationSpan), null, ValueStack[ValueStack.Depth-2].td as type_definition, CurrentLocationSpan);
		}
        break;
      case 69: // proc_func_call -> variable, LPAR, optional_expr_lst, RPAR
{ 
			CurrentSemanticValue.ex = new method_call(ValueStack[ValueStack.Depth-4].ex as addressed_value, ValueStack[ValueStack.Depth-2].stn as expression_list, CurrentLocationSpan); 
		}
        break;
      case 70: // simple_type_identifier -> identifier
{
			switch (ValueStack[ValueStack.Depth-1].id.name) {
				case "int":
					CurrentSemanticValue.td = new named_type_reference("integer", CurrentLocationSpan);
					break;
				case "float":
					CurrentSemanticValue.td = new named_type_reference("real", CurrentLocationSpan);
					break;
				case "str":
					CurrentSemanticValue.td = new named_type_reference("string", CurrentLocationSpan);
					break;
				
				case "integer":
				case "real":
				case "string":
					CurrentSemanticValue.td = new named_type_reference("error", CurrentLocationSpan);
					break;
				
				default:
					CurrentSemanticValue.td = new named_type_reference(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
					break;
			}
		}
        break;
      case 71: // range_expr -> simple_type_identifier
{
			CurrentSemanticValue.ex = parsertools.ConvertNamedTypeReferenceToDotNodeOrIdent(ValueStack[ValueStack.Depth-1].td as named_type_reference);
		}
        break;
      case 72: // fp_type -> range_expr
{ 
			CurrentSemanticValue.td = parsertools.ConvertDotNodeOrIdentToNamedTypeReference(ValueStack[ValueStack.Depth-1].ex); 
		}
        break;
      case 73: // param_name -> identifier
{
			symbolTable.Add(ValueStack[ValueStack.Depth-1].id.name);
			CurrentSemanticValue.stn = new ident_list(ValueStack[ValueStack.Depth-1].id, CurrentLocationSpan);
		}
        break;
      case 74: // simple_fp_sect -> param_name, COLON, fp_type
{
			CurrentSemanticValue.stn = new typed_parameters(ValueStack[ValueStack.Depth-3].stn as ident_list, ValueStack[ValueStack.Depth-1].td, parametr_kind.none, null, CurrentLocationSpan); 
		}
        break;
      case 75: // fp_sect -> simple_fp_sect
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn; 
		}
        break;
      case 76: // fp_sect_list -> fp_sect
{ 
			CurrentSemanticValue.stn = new formal_parameters(ValueStack[ValueStack.Depth-1].stn as typed_parameters, CurrentLocationSpan);
        }
        break;
      case 77: // fp_sect_list -> fp_sect_list, COMMA, fp_sect
{ 
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as formal_parameters).Add(ValueStack[ValueStack.Depth-1].stn as typed_parameters, CurrentLocationSpan);   
        }
        break;
      case 78: // fp_list -> LPAR, RPAR
{
			CurrentSemanticValue.stn = null; 
		}
        break;
      case 79: // fp_list -> LPAR, fp_sect_list, RPAR
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-2].stn;
			if (CurrentSemanticValue.stn != null)
				CurrentSemanticValue.stn.source_context = CurrentLocationSpan;
		}
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


        public program_module NewProgramModule(program_name progName, Object optHeadCompDirs, uses_list mainUsesClose, syntax_tree_node progBlock, Object optPoint, LexLocation loc)
        {
            var progModule = new program_module(progName, mainUsesClose, progBlock as block, null, loc);
            progModule.Language = LanguageId.SPython;
            if (optPoint == null && progBlock != null)
            {
                var fp = progBlock.source_context.end_position;
                var err_stn = progBlock;
			    if ((progBlock is block) && (progBlock as block).program_code != null && (progBlock as block).program_code.subnodes != null && (progBlock as block).program_code.subnodes.Count > 0)
                    err_stn = (progBlock as block).program_code.subnodes[(progBlock as block).program_code.subnodes.Count - 1];
                parsertools.errors.Add(new SPythonUnexpectedToken(parsertools.CurrentFileName, StringResources.Get("TKPOINT"), new SourceContext(fp.line_num, fp.column_num + 1, fp.line_num, fp.column_num + 1, 0, 0), err_stn));
            }
            return progModule;
        }
}
}
