// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.3.6
// Machine:  DESKTOP-V3E9T2U
// DateTime: 07.11.2025 18:14:05
// UserName: alex
// Input file <ExampleParser.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using PascalABCCompiler.SyntaxTree;
using PascalABCCompiler.ParserTools;

namespace Languages.Example.Frontend.Core
{
public enum Tokens {
    error=1,EOF=2,VAR=3,ASSIGN=4,SEMICOLON=5,LPAR=6,
    RPAR=7,INTNUM=8,ID=9};

// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<PascalABCCompiler.ParserTools.Union,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public partial class ExampleGPPGParser: ShiftReduceParser<PascalABCCompiler.ParserTools.Union, LexLocation>
{
  // Verbatim content from ExampleParser.y
   	internal syntax_tree_node root;
	internal ExampleParserTools parserTools;

	internal ExampleGPPGParser(AbstractScanner<Union, LexLocation> scanner, ExampleParserTools parserTools) : base(scanner)
	{ 
		this.parserTools = parserTools;
	}
  // End verbatim content from ExampleParser.y

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[12];
  private static State[] states = new State[21];
  private static string[] nonTerms = new string[] {
      "program", "stmt_list", "stmt", "var_stmt", "proc_func_call", "ident", 
      "param", "$accept", };

  static ExampleGPPGParser() {
    states[0] = new State(new int[]{3,7,9,11},new int[]{-1,1,-2,3,-3,19,-4,6,-5,12,-6,13});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{3,7,9,11,2,-2},new int[]{-3,4,-4,6,-5,12,-6,13});
    states[4] = new State(new int[]{5,5});
    states[5] = new State(-4);
    states[6] = new State(-5);
    states[7] = new State(new int[]{9,11},new int[]{-6,8});
    states[8] = new State(new int[]{4,9});
    states[9] = new State(new int[]{8,10});
    states[10] = new State(-7);
    states[11] = new State(-11);
    states[12] = new State(-6);
    states[13] = new State(new int[]{6,14});
    states[14] = new State(new int[]{9,11,8,18},new int[]{-7,15,-6,17});
    states[15] = new State(new int[]{7,16});
    states[16] = new State(-8);
    states[17] = new State(-9);
    states[18] = new State(-10);
    states[19] = new State(new int[]{5,20});
    states[20] = new State(-3);

    rules[1] = new Rule(-8, new int[]{-1,2});
    rules[2] = new Rule(-1, new int[]{-2});
    rules[3] = new Rule(-2, new int[]{-3,5});
    rules[4] = new Rule(-2, new int[]{-2,-3,5});
    rules[5] = new Rule(-3, new int[]{-4});
    rules[6] = new Rule(-3, new int[]{-5});
    rules[7] = new Rule(-4, new int[]{3,-6,4,8});
    rules[8] = new Rule(-5, new int[]{-6,6,-7,7});
    rules[9] = new Rule(-7, new int[]{-6});
    rules[10] = new Rule(-7, new int[]{8});
    rules[11] = new Rule(-6, new int[]{9});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // program -> stmt_list
{
			// main program
			var stl = ValueStack[ValueStack.Depth-1].stn as statement_list;
            stl.left_logical_bracket = new token_info("");
            stl.right_logical_bracket = new token_info("");
            
            var bl = new block(new declarations(), stl, CurrentLocationSpan);
            
            root = CurrentSemanticValue.stn = NewProgramModule(bl, CurrentLocationSpan);
        }
        break;
      case 3: // stmt_list -> stmt, SEMICOLON
{ 
			CurrentSemanticValue.stn = new statement_list(ValueStack[ValueStack.Depth-2].stn as statement, LocationStack[LocationStack.Depth-2]);
        }
        break;
      case 4: // stmt_list -> stmt_list, stmt, SEMICOLON
{  
			CurrentSemanticValue.stn = (ValueStack[ValueStack.Depth-3].stn as statement_list).Add(ValueStack[ValueStack.Depth-2].stn as statement, CurrentLocationSpan);
        }
        break;
      case 5: // stmt -> var_stmt
{ 
			CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn;
		}
        break;
      case 6: // stmt -> proc_func_call
{
            CurrentSemanticValue.stn = ValueStack[ValueStack.Depth-1].stn;
        }
        break;
      case 7: // var_stmt -> VAR, ident, ASSIGN, INTNUM
{ 
			CurrentSemanticValue.stn = new var_statement(new var_def_statement(new ident_list(ValueStack[ValueStack.Depth-3].id), null, ValueStack[ValueStack.Depth-1].ex, definition_attribute.None, false, CurrentLocationSpan));
		}
        break;
      case 8: // proc_func_call -> ident, LPAR, param, RPAR
{
			CurrentSemanticValue.stn = new procedure_call(new method_call(ValueStack[ValueStack.Depth-4].id as addressed_value, new expression_list(ValueStack[ValueStack.Depth-2].ex, CurrentLocationSpan)), true, CurrentLocationSpan);
		}
        break;
      case 9: // param -> ident
{
            CurrentSemanticValue.ex = ValueStack[ValueStack.Depth-1].id;
        }
        break;
      case 11: // ident -> ID
{
			CurrentSemanticValue.id = ValueStack[ValueStack.Depth-1].id;
		}
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


public program_module NewProgramModule(block progBlock, LexLocation loc)
{
    var progModule = new program_module(null, new uses_list(), progBlock, null, loc);

    progModule.source_context = progBlock.source_context;

    return progModule;
}
}
}
