<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net472;net10.0</TargetFrameworks>
    <AssemblyName>PABCCompilerController</AssemblyName>
    <RootNamespace>PascalABCNet.CompilerController</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472"
                      Version="1.0.3"
                      PrivateAssets="all" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
