unit u_binfile2;
var f : file;
begin
Assign(f,'test.dat');
Rewrite(f);
Write(f,2);
Write(f,2.3);
Write(f,'Privet');
var s1 : string[5] := 'Bye';
Write(f,s1);
var arr : array[1..3] of integer := (2,3,4);
Write(f,arr);
Close(f);
Reset(f);
var i : integer;
Read(f,i);
assert(i=2);
var r : real;
Read(f,r);
assert(r=2.3);
var s : string;
Read(f,s);
assert(s='Privet');
s1 := '';
Read(f,s1);
assert(s1='Bye');
arr[1] := 0; arr[2] := 0; arr[3] := 0;
Read(f,arr);
assert(arr[3]=4);
Close(f);
end.