unit u_case4;
var a,b : char;
begin
a := 'l';
case a of
'A': b := 'A';
'B': b := 'B';
'C': b := 'C';
'D': b := 'D';
'E': b := 'E';
'F': b := 'F';
'G': b := 'G';
'H': b := 'H';
'I': b := 'I';
'J': b := 'J';
'K': b := 'K';
'L': b := 'L';
'M': b := 'M';
'N': b := 'N';
'O': b := 'O';
'P': b := 'P';
'Q': b := 'Q';
'R': b := 'R';
'S': b := 'S';
'T': b := 'T';
'U': b := 'U';
'V': b := 'V';
'W': b := 'W';
'X': b := 'X';
'Y': b := 'Y';
'Z': b := 'Z';
'a': b := 'a';
'b': b := 'b';
'c': b := 'c';
'd': b := 'd';
'e': b := 'e';
'f': b := 'f';
'g': b := 'g';
'h': b := 'h';
'i': b := 'i';
'j': b := 'j';
'k': b := 'k';
'l': b := 'l';
'm': b := 'm';
'n': b := 'n';
'o': b := 'o';
'p': b := 'p';
'q': b := 'q';
'r': b := 'r';
's': b := 's';
't': b := 't';
'u': b := 'u';
'v': b := 'v';
'w': b := 'w';
'x': b := 'x';
'y': b := 'y';
'z': b := 'z';
end;
assert(b='l')
end.
