<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks Condition="'$(PABCNET_LEGACY_ONLY)' != 'true'">net40;net10.0</TargetFrameworks>
    <TargetFramework Condition="'$(PABCNET_LEGACY_ONLY)' == 'true'">net40</TargetFramework>
    
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    
    <BaseOutputPath>$(OutputPath)</BaseOutputPath>
  </PropertyGroup>
</Project>
