const 
  uint32MaxValue=$FFFFFFFF;
  uint64MaxValue=$FFFFFFFFFFFFFFFF;

begin
  writeln(system.char.MinValue);
  writeln(system.sbyte.MinValue);
  writeln(system.byte.MinValue);
  writeln(system.int16.MinValue);
  writeln(system.uint16.MinValue);
  writeln(system.int32.MinValue);
  writeln(system.uint32.MinValue);
  writeln(system.int64.MinValue);
  writeln(system.uint64.MinValue);
  writeln(system.single.MinValue);
  writeln(system.double.MinValue);

  writeln(system.char.MaxValue);
  writeln(system.sbyte.MaxValue);
  writeln(system.byte.MaxValue);
  writeln(system.int16.MaxValue);
  writeln(system.uint16.MaxValue);
  writeln(system.int32.MaxValue);
  writeln(uint32MaxValue);
  writeln(system.uint32.MaxValue);
  writeln(system.int64.MaxValue);
  writeln(uint64MaxValue);
  writeln(system.uint64.MaxValue);
  writeln(system.single.MaxValue);
  writeln(system.double.MaxValue);
end.