program test0166(input, output);

var b : byte := 1;
    c : char := 'k';
    sh : shortint := 3;
    sm : smallint := 4;
    w : word := 5;
    i : integer := 6;
    lw : longword := 7;
    li : int64 := 8;
    ul : uint64 := 9;
    s : string := 'ka';
    s2 : string[4] := 'ljk';
begin
  assign(output,'out.txt');
  writeln(b);
  writeln(c);
  writeln(sh);
  writeln(sm);
  writeln(w);
  writeln(i);
  writeln(lw);
  writeln(li);
  writeln(ul);
  writeln(s);
  writeln(s2);
  s := '1234567';
  writeln(s);
  close(output);
  writeln('privet');
  b := 0;
  c := ' ';
  sh := 0;
  sm := 0;
  w := 0; i := 0; lw := 0; li :=0; ul := 0; s := ''; s2 := '';
  assign(input,'out.txt');
  readln(b); assert(b=1);
  readln(c); assert(c='k');
  readln(sh); assert(sh=3);
  readln(sm); assert(sm=4);
  readln(w); assert(w=5);
  readln(i); assert(i=6);
  readln(lw); assert(lw=7);
  readln(li); assert(li=8);
  readln(ul); assert(ul=9);
  readln(s); assert(s='ka');
  readln(s2); assert(s2='ljk');
  readln(s2); assert(s2='1234');
  close(input);
end.