name: Build & Publish (release)

on:
  workflow_dispatch:
  push:
    branches:
      - test
  release:
    types:
      - created

defaults:
  run:
    shell: cmd

jobs:
  build:

    name: Prepare and build on Windows Server VM (2019)
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies into Virtual Environment...
      run: _RegisterHelixNUnit.bat

    - name: Build project in Release-mode, compile Pas-units, create install packages...
      run: _GenerateAllSetups.bat
      timeout-minutes: 45
      env:
        PABCNET_BUILD_MODE: Release
        PABCNET_RUN_TESTS:  false
        PABCNET_INC_BUILD:  false
        PABCNET_VERBOSE:    false

    - name: Publish artifacts (1/4)...
      uses: actions/upload-artifact@v4
      with:
        name: PascalABCNET_Win7_IDE_Full
        path: Release/PascalABCNETSetup.exe
        if-no-files-found: error

    - name: Publish artifacts (2/4)...
      uses: actions/upload-artifact@v4
      with:
        name: PascalABCNET_Win7_IDE_Mini
        path: Release/PascalABCNETMiniSetup.exe
        if-no-files-found: error

    - name: Publish artifacts (3/4)...
      uses: actions/upload-artifact@v4
      with:
        name: PascalABCNET_WinXP_IDE_Full
        path: Release/PascalABCNETWithDotNet40Setup.exe
        if-no-files-found: error

    - name: Publish artifacts (4/4)...
      uses: actions/upload-artifact@v4
      with:
        name: PascalABCNET_Win_Mac_Linux_console
        path: Release/PABCNETC.zip
        if-no-files-found: error

    #- name: Publish artifacts (5/5)...
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: All_distros
    #    path: Release
    #    if-no-files-found: error
